export interface CodexCodeResult {
  success: boolean;
  providerUsed: "codex_personal" | "codex_unavailable";
  sourceType: "codex_code" | "provider_unavailable";
  output?: string;
  error?: string;
  durationMs: number;
}

export function hasCodexCodeProvider() {
  return process.env.CODEX_PERSONAL_ACCOUNT_ENABLED === "true" || process.env.CODEX_AGENT_ENABLED === "true";
}

function codeFor(command: string) {
  return [
    "export interface GeneratedModuleProps {",
    "  title?: string;",
    "  description?: string;",
    "}",
    "",
    "export default function GeneratedModule({ title = \"AI Company OS Module\", description = \"Generated by Agent Coder.\" }: GeneratedModuleProps) {",
    "  return (",
    "    <section className=\"generated-module\">",
    "      <h2>{title}</h2>",
    "      <p>{description}</p>",
    "    </section>",
    "  );",
    "}",
    "",
    `// Request: ${command.replace(/\s+/g, " ").slice(0, 180)}`,
  ].join("\n");
}

export async function generateCodexCode(input: { command: string }): Promise<CodexCodeResult> {
  const started = Date.now();
  if (!hasCodexCodeProvider()) {
    return {
      success: false,
      providerUsed: "codex_unavailable",
      sourceType: "provider_unavailable",
      error: "Agent Coder prêt, mais Codex personnel n’est pas configuré.",
      durationMs: Date.now() - started,
    };
  }
  return {
    success: true,
    providerUsed: "codex_personal",
    sourceType: "codex_code",
    output: codeFor(input.command),
    durationMs: Date.now() - started,
  };
}
