import fs from "fs";
import path from "path";
import type { AutopilotSession } from "./autopilotStore";

// ─── Paths ────────────────────────────────────────────────────────────────────

const REPO_ROOT = path.resolve(process.cwd(), "..");
const WORKSPACES_ROOT = path.join(REPO_ROOT, "generated", "autopilot-workspaces");

function workspaceDir(sessionId: string): string {
  return path.join(WORKSPACES_ROOT, sessionId);
}

function ensureDir(dir: string) {
  fs.mkdirSync(dir, { recursive: true });
}

function safeWriteFile(filePath: string, content: string) {
  ensureDir(path.dirname(filePath));
  fs.writeFileSync(filePath, content, "utf-8");
}

function formatTimestamp(iso: string): string {
  try {
    return new Date(iso).toISOString().replace("T", " ").slice(0, 19);
  } catch {
    return iso;
  }
}

// ─── Types ────────────────────────────────────────────────────────────────────

export interface DeliverableFile {
  path: string;
  name: string;
  size: number;
  modifiedAt: string;
}

type DeliverableSpec = {
  path: string;
  content: (session: AutopilotSession) => string;
};

// ─── Deliverable Specs ────────────────────────────────────────────────────────

const DELIVERABLE_SPECS: Record<string, DeliverableSpec[]> = {
  website: [
    {
      path: "deliverables/website/site-map.md",
      content: (s) => [
        `# Site Map — ${s.projectName}`,
        "",
        `**Session:** ${s.sessionId}`,
        `**Date:** ${formatTimestamp(s.updatedAt)}`,
        "",
        "## Pages",
        "",
        "| Page | URL | Purpose |",
        "|------|-----|---------|",
        "| Home | / | Landing page and hero |",
        "| About | /about | Company or personal story |",
        "| Services | /services | Offerings and features |",
        "| Blog | /blog | Articles and updates |",
        "| Contact | /contact | Contact form and info |",
        "",
        "## Navigation",
        "",
        "- Primary: Home, About, Services, Blog, Contact",
        "- Footer: Privacy, Terms, Social links",
        "",
        `_Generated by AI Company OS — ${s.projectName}_`,
        "",
      ].join("\n"),
    },
    {
      path: "deliverables/website/homepage-copy.md",
      content: (s) => [
        `# Homepage Copy — ${s.projectName}`,
        "",
        `**Session:** ${s.sessionId}`,
        `**Date:** ${formatTimestamp(s.updatedAt)}`,
        "",
        "## Hero Section",
        "",
        "### Headline",
        `${s.projectName} — ${s.projectIdea.split(".")[0]}`,
        "",
        "### Subheadline",
        `${s.projectIdea}`,
        "",
        "### CTA",
        "- Primary: Get Started",
        "- Secondary: Learn More",
        "",
        "## Features Section",
        "",
        "1. **Fast** — Deliver results in record time",
        "2. **Reliable** — Built to last, tested thoroughly",
        "3. **Simple** — Intuitive from day one",
        "",
        `_Generated by AI Company OS — ${s.projectName}_`,
        "",
      ].join("\n"),
    },
    {
      path: "deliverables/website/sections.md",
      content: (s) => [
        `# Page Sections — ${s.projectName}`,
        "",
        `**Session:** ${s.sessionId}`,
        `**Date:** ${formatTimestamp(s.updatedAt)}`,
        "",
        "## Section Breakdown",
        "",
        "### Homepage",
        "1. Hero — Headline, subtext, CTA, hero image",
        "2. Features — 3-column grid with icons",
        "3. Testimonials — 3 quote cards",
        "4. Pricing — 3-tier table",
        "5. CTA Banner — Final conversion section",
        "6. Footer — Links, social, legal",
        "",
        "### About",
        "1. Story — Company or personal origin",
        "2. Team — Photos and bios",
        "3. Values — Core principles",
        "",
        `_Generated by AI Company OS — ${s.projectName}_`,
        "",
      ].join("\n"),
    },
  ],

  branding_pack: [
    {
      path: "deliverables/branding/brand-strategy.md",
      content: (s) => [
        `# Brand Strategy — ${s.projectName}`,
        "",
        `**Session:** ${s.sessionId}`,
        `**Date:** ${formatTimestamp(s.updatedAt)}`,
        "",
        "## Brand Positioning",
        "",
        `**Brand Name:** ${s.projectName}`,
        `**Tagline:** ${s.projectIdea.split(".")[0]}`,
        "",
        "## Brand Pillars",
        "",
        "1. **Authenticity** — Genuine, transparent communication",
        "2. **Innovation** — Forward-thinking design and messaging",
        "3. **Trust** — Consistent quality across all touchpoints",
        "",
        "## Target Audience",
        "",
        `- Primary: ${s.productType ?? "Modern professionals and businesses"}`,
        "- Secondary: Early adopters seeking premium alternatives",
        "",
        "## Tone of Voice",
        "",
        "- Clear and direct",
        "- Confident but approachable",
        "- Expert without being technical",
        "",
        `_Generated by AI Company OS — ${s.projectName}_`,
        "",
      ].join("\n"),
    },
    {
      path: "deliverables/branding/logo-brief.md",
      content: (s) => [
        `# Logo Brief — ${s.projectName}`,
        "",
        `**Session:** ${s.sessionId}`,
        `**Date:** ${formatTimestamp(s.updatedAt)}`,
        "",
        "## Logo Requirements",
        "",
        `**Brand:** ${s.projectName}`,
        "**Style:** Minimal, modern, timeless",
        "",
        "## Variants Needed",
        "",
        "| Variant | Usage |",
        "|---------|-------|",
        "| Primary | Main logo with wordmark |",
        "| Secondary | Icon-only mark |",
        "| Horizontal | Wide layouts and headers |",
        "| Favicon | 16×16 and 32×32 px |",
        "| Dark | White version for dark backgrounds |",
        "",
        "## Design Direction",
        "",
        "- Geometric or abstract mark",
        "- Sans-serif wordmark",
        "- Avoid: gradients, drop shadows, more than 2 colors",
        "",
        "## File Formats",
        "",
        "- SVG (primary, scalable)",
        "- PNG (transparent, @1x / @2x)",
        "- PDF (print-ready)",
        "",
        `_Generated by AI Company OS — ${s.projectName}_`,
        "",
      ].join("\n"),
    },
    {
      path: "deliverables/branding/colors-typography.md",
      content: (s) => [
        `# Colors & Typography — ${s.projectName}`,
        "",
        `**Session:** ${s.sessionId}`,
        `**Date:** ${formatTimestamp(s.updatedAt)}`,
        "",
        "## Color Palette",
        "",
        "| Role | Hex | Usage |",
        "|------|-----|-------|",
        "| Primary | #6366F1 | Main brand color, CTAs, headers |",
        "| Secondary | #818CF8 | Accents, hover states |",
        "| Neutral Dark | #0F172A | Background, text |",
        "| Neutral Light | #F8FAFC | Light background, cards |",
        "| Success | #34D399 | Positive states |",
        "| Error | #F43F5E | Error states, alerts |",
        "",
        "## Typography",
        "",
        "| Role | Font | Size | Weight |",
        "|------|------|------|--------|",
        "| Heading 1 | Inter | 48px | 800 |",
        "| Heading 2 | Inter | 32px | 700 |",
        "| Heading 3 | Inter | 24px | 600 |",
        "| Body | Inter | 16px | 400 |",
        "| Caption | Inter | 12px | 400 |",
        "| Code | ui-monospace | 13px | 400 |",
        "",
        "## Spacing System",
        "",
        "- Base unit: 4px",
        "- Scale: 4, 8, 12, 16, 24, 32, 48, 64, 96",
        "",
        `_Generated by AI Company OS — ${s.projectName}_`,
        "",
      ].join("\n"),
    },
  ],

  flyer: [
    {
      path: "deliverables/flyer/flyer-copy.md",
      content: (s) => [
        `# Flyer Copy — ${s.projectName}`,
        "",
        `**Session:** ${s.sessionId}`,
        `**Date:** ${formatTimestamp(s.updatedAt)}`,
        "",
        "## Headline",
        "",
        `**${s.projectName}**`,
        "",
        "## Subheadline",
        "",
        `${s.projectIdea.split(".")[0]}`,
        "",
        "## Body Copy",
        "",
        `${s.projectIdea}`,
        "",
        "## Call to Action",
        "",
        "- **Primary CTA:** Contact us today",
        "- **Secondary CTA:** Visit our website",
        "",
        "## Contact Info",
        "",
        "- Website: www.example.com",
        "- Email: hello@example.com",
        "- Phone: +1 (555) 000-0000",
        "",
        `_Generated by AI Company OS — ${s.projectName}_`,
        "",
      ].join("\n"),
    },
    {
      path: "deliverables/flyer/layout-brief.md",
      content: (s) => [
        `# Layout Brief — ${s.projectName} Flyer`,
        "",
        `**Session:** ${s.sessionId}`,
        `**Date:** ${formatTimestamp(s.updatedAt)}`,
        "",
        "## Format",
        "",
        "| Property | Value |",
        "|----------|-------|",
        "| Size | A4 (210 × 297 mm) / Letter (8.5 × 11 in) |",
        "| Orientation | Portrait |",
        "| Sides | Single-sided |",
        "| Bleed | 3mm all around |",
        "",
        "## Layout Zones",
        "",
        "1. **Top third** — Hero image or brand graphic",
        "2. **Middle** — Headline + body copy",
        "3. **Bottom** — CTA + contact info",
        "",
        "## Visual Direction",
        "",
        "- High contrast background",
        "- Bold headline typography",
        "- Single focal image or illustration",
        "- Brand colors for accents",
        "",
        `_Generated by AI Company OS — ${s.projectName}_`,
        "",
      ].join("\n"),
    },
    {
      path: "deliverables/flyer/print-specs.md",
      content: (s) => [
        `# Print Specifications — ${s.projectName} Flyer`,
        "",
        `**Session:** ${s.sessionId}`,
        `**Date:** ${formatTimestamp(s.updatedAt)}`,
        "",
        "## Technical Specs",
        "",
        "| Spec | Value |",
        "|------|-------|",
        "| Resolution | 300 DPI minimum |",
        "| Color Mode | CMYK for print / RGB for digital |",
        "| Bleed | 3mm all sides |",
        "| Safe Zone | 5mm from trim edge |",
        "| File Format | PDF/X-1a (print), PNG (digital) |",
        "",
        "## Paper & Finishing",
        "",
        "| Option | Recommendation |",
        "|--------|---------------|",
        "| Paper Weight | 135–170 gsm |",
        "| Paper Stock | Gloss or silk coated |",
        "| Finishing | UV spot gloss on headline |",
        "",
        "## Pre-Press Checklist",
        "",
        "- [ ] Bleed applied (3mm)",
        "- [ ] Fonts embedded or outlined",
        "- [ ] Images at 300 DPI",
        "- [ ] Color mode: CMYK",
        "- [ ] Spell-check complete",
        "- [ ] Proofed at 100% scale",
        "",
        `_Generated by AI Company OS — ${s.projectName}_`,
        "",
      ].join("\n"),
    },
  ],

  business_card: [
    {
      path: "deliverables/business-card/card-copy.md",
      content: (s) => [
        `# Business Card Copy — ${s.projectName}`,
        "",
        `**Session:** ${s.sessionId}`,
        `**Date:** ${formatTimestamp(s.updatedAt)}`,
        "",
        "## Front Side",
        "",
        "**Name:** [Full Name]",
        "**Title:** [Job Title]",
        `**Company:** ${s.projectName}`,
        "",
        "## Back Side",
        "",
        "**Contact Information:**",
        "- Email: hello@example.com",
        "- Phone: +1 (555) 000-0000",
        "- Website: www.example.com",
        "- LinkedIn: linkedin.com/in/name",
        "",
        "## Brand Elements",
        "",
        `- Logo: ${s.projectName} wordmark`,
        "- Tagline: Optional, max 6 words",
        "",
        `_Generated by AI Company OS — ${s.projectName}_`,
        "",
      ].join("\n"),
    },
    {
      path: "deliverables/business-card/layout-brief.md",
      content: (s) => [
        `# Layout Brief — ${s.projectName} Business Card`,
        "",
        `**Session:** ${s.sessionId}`,
        `**Date:** ${formatTimestamp(s.updatedAt)}`,
        "",
        "## Format",
        "",
        "| Property | Value |",
        "|----------|-------|",
        "| Size | Standard 85 × 55 mm (3.5 × 2 in) |",
        "| Orientation | Landscape |",
        "| Sides | Double-sided |",
        "| Corners | Square / Rounded 3mm |",
        "",
        "## Layout Zones",
        "",
        "**Front:**",
        "- Top: Logo mark",
        "- Center: Name (large), Title (small)",
        "- Bottom: Company name / tagline",
        "",
        "**Back:**",
        "- Full color background or pattern",
        "- Contact info centered",
        "",
        "## Visual Direction",
        "",
        "- Minimal white space",
        "- One accent color",
        "- Single typeface (2 weights max)",
        "",
        `_Generated by AI Company OS — ${s.projectName}_`,
        "",
      ].join("\n"),
    },
    {
      path: "deliverables/business-card/print-specs.md",
      content: (s) => [
        `# Print Specifications — ${s.projectName} Business Card`,
        "",
        `**Session:** ${s.sessionId}`,
        `**Date:** ${formatTimestamp(s.updatedAt)}`,
        "",
        "## Technical Specs",
        "",
        "| Spec | Value |",
        "|------|-------|",
        "| Resolution | 300 DPI minimum |",
        "| Color Mode | CMYK |",
        "| Bleed | 3mm all sides |",
        "| Safe Zone | 3mm from trim edge |",
        "| File Format | PDF/X-1a |",
        "",
        "## Paper & Finishing",
        "",
        "| Option | Recommendation |",
        "|--------|---------------|",
        "| Paper Weight | 350–400 gsm |",
        "| Paper Stock | Silk laminated |",
        "| Finishing | Spot UV gloss on logo |",
        "",
        "## Pre-Press Checklist",
        "",
        "- [ ] Bleed applied (3mm)",
        "- [ ] Fonts embedded or outlined",
        "- [ ] All images at 300 DPI",
        "- [ ] Color mode: CMYK",
        "- [ ] Spell-check: name, email, phone",
        "- [ ] Contact info verified",
        "",
        `_Generated by AI Company OS — ${s.projectName}_`,
        "",
      ].join("\n"),
    },
  ],

  ecommerce_store: [
    {
      path: "deliverables/ecommerce/store-plan.md",
      content: (s) => [
        `# Store Plan — ${s.projectName}`,
        "",
        `**Session:** ${s.sessionId}`,
        `**Date:** ${formatTimestamp(s.updatedAt)}`,
        "",
        "## Store Overview",
        "",
        `**Store Name:** ${s.projectName}`,
        `**Concept:** ${s.projectIdea.split(".")[0]}`,
        "",
        "## Product Categories",
        "",
        "1. Category A — Core products",
        "2. Category B — Accessories",
        "3. Category C — Bundles and kits",
        "",
        "## Customer Journey",
        "",
        "1. Discovery — SEO, ads, social",
        "2. Browse — Category and product pages",
        "3. Add to Cart — Product detail page",
        "4. Checkout — Cart → Shipping → Payment",
        "5. Confirmation — Order email + account",
        "6. Retention — Post-purchase email",
        "",
        "## Revenue Model",
        "",
        "- Primary: Direct product sales",
        "- Secondary: Subscription / repeat orders",
        "- Upsell: Related products, bundles",
        "",
        `_Generated by AI Company OS — ${s.projectName}_`,
        "",
      ].join("\n"),
    },
    {
      path: "deliverables/ecommerce/product-research.md",
      content: (s) => [
        `# Product Research — ${s.projectName}`,
        "",
        `**Session:** ${s.sessionId}`,
        `**Date:** ${formatTimestamp(s.updatedAt)}`,
        "",
        "## Market Analysis",
        "",
        `**Target Market:** ${s.productType ?? "Direct-to-consumer"}`,
        `**Brief:** ${s.projectIdea}`,
        "",
        "## Competitor Analysis",
        "",
        "| Competitor | Strengths | Weaknesses | Price Range |",
        "|-----------|-----------|------------|-------------|",
        "| Competitor A | Brand recognition | High prices | $$$ |",
        "| Competitor B | Low price | Poor UX | $ |",
        "| Competitor C | Wide selection | Slow shipping | $$ |",
        "",
        "## Product Validation",
        "",
        "- Search volume for key terms: High",
        "- Social proof: Active communities",
        "- Profit margin target: 40–60%",
        "",
        "## Pricing Strategy",
        "",
        "- Penetration: Launch at 20% below market",
        "- Value: Premium positioning with quality signal",
        "- Bundle: Multi-unit discounts for retention",
        "",
        `_Generated by AI Company OS — ${s.projectName}_`,
        "",
      ].join("\n"),
    },
    {
      path: "deliverables/ecommerce/ads-plan.md",
      content: (s) => [
        `# Ads Plan — ${s.projectName}`,
        "",
        `**Session:** ${s.sessionId}`,
        `**Date:** ${formatTimestamp(s.updatedAt)}`,
        "",
        "## Advertising Strategy",
        "",
        `**Goal:** Drive qualified traffic to ${s.projectName} store`,
        "",
        "## Channels",
        "",
        "| Channel | Budget % | Objective | KPI |",
        "|---------|----------|-----------|-----|",
        "| Google Shopping | 35% | Purchase intent | ROAS > 3× |",
        "| Meta (FB/IG) | 35% | Awareness + conversion | CPA < $25 |",
        "| TikTok | 20% | Discovery | CTR > 2% |",
        "| Email Retargeting | 10% | Cart recovery | Open rate > 30% |",
        "",
        "## Creative Requirements",
        "",
        "- Product hero images (white background)",
        "- Lifestyle images (in-use context)",
        "- Video: 15s and 30s formats",
        "- Copy: Short, benefit-led headlines",
        "",
        "## Launch Timeline",
        "",
        "1. Week 1: Set up accounts, pixels, tracking",
        "2. Week 2: Launch broad testing campaigns",
        "3. Week 3: Scale winning ad sets",
        "4. Week 4: Optimize ROAS and CPA",
        "",
        `_Generated by AI Company OS — ${s.projectName}_`,
        "",
      ].join("\n"),
    },
  ],

  social_campaign: [
    {
      path: "deliverables/social/content-calendar.md",
      content: (s) => [
        `# Content Calendar — ${s.projectName}`,
        "",
        `**Session:** ${s.sessionId}`,
        `**Date:** ${formatTimestamp(s.updatedAt)}`,
        "",
        "## Campaign Overview",
        "",
        `**Campaign:** ${s.projectName}`,
        `**Goal:** ${s.projectIdea.split(".")[0]}`,
        "",
        "## Weekly Posting Schedule",
        "",
        "| Day | Platform | Content Type | Theme |",
        "|-----|----------|-------------|-------|",
        "| Monday | Instagram | Carousel | Tips & Insights |",
        "| Tuesday | LinkedIn | Article | Industry Thought Leadership |",
        "| Wednesday | TikTok | Short Video | Behind the Scenes |",
        "| Thursday | Instagram | Story | Poll / Engagement |",
        "| Friday | All | Promotional | Offer / CTA |",
        "| Saturday | Instagram | Reel | Entertainment |",
        "| Sunday | LinkedIn | Curated | Community Pick |",
        "",
        "## Content Pillars",
        "",
        "1. **Education** (30%) — Tips, how-tos, insights",
        "2. **Entertainment** (25%) — Relatable, fun, shareable",
        "3. **Inspiration** (20%) — Success stories, quotes",
        "4. **Promotion** (25%) — Products, offers, CTAs",
        "",
        `_Generated by AI Company OS — ${s.projectName}_`,
        "",
      ].join("\n"),
    },
    {
      path: "deliverables/social/ad-copy.md",
      content: (s) => [
        `# Ad Copy — ${s.projectName}`,
        "",
        `**Session:** ${s.sessionId}`,
        `**Date:** ${formatTimestamp(s.updatedAt)}`,
        "",
        "## Ad Variations",
        "",
        "### Variation A — Problem/Solution",
        "**Hook:** Tired of [problem]?",
        `**Body:** ${s.projectIdea}`,
        "**CTA:** Learn More →",
        "",
        "### Variation B — Benefit-Led",
        `**Hook:** Introducing ${s.projectName}`,
        `**Body:** ${s.projectIdea.split(".")[0]}. Built for people who want results.`,
        "**CTA:** Get Started Free →",
        "",
        "### Variation C — Social Proof",
        `**Hook:** Join thousands using ${s.projectName}`,
        `**Body:** ${s.projectIdea}`,
        "**CTA:** See How It Works →",
        "",
        "## Hashtag Strategy",
        "",
        `- Brand: #${s.projectName.toLowerCase().replace(/[\s-]+/g, "")}`,
        "- Category: #innovation #design #growth",
        "- Trending: Research weekly before posting",
        "",
        `_Generated by AI Company OS — ${s.projectName}_`,
        "",
      ].join("\n"),
    },
    {
      path: "deliverables/social/post-ideas.md",
      content: (s) => [
        `# Post Ideas — ${s.projectName}`,
        "",
        `**Session:** ${s.sessionId}`,
        `**Date:** ${formatTimestamp(s.updatedAt)}`,
        "",
        "## Content Bank (15 Ideas)",
        "",
        "### Educational",
        `1. 5 ways ${s.projectName} saves you time`,
        `2. How we built ${s.projectName} in 30 days`,
        "3. Common mistakes people make with [topic]",
        "4. Behind the scenes: a day in the life",
        "5. Industry trends to watch this year",
        "",
        "### Engagement",
        "6. Poll: Which feature do you use most?",
        `7. Tag someone who needs ${s.projectName}`,
        "8. True or False: [controversial opinion]",
        "9. Would you rather: A or B?",
        "10. Caption this photo →",
        "",
        "### Promotional",
        `11. Why we built ${s.projectName}`,
        "12. Customer spotlight: success story",
        "13. Limited offer: 20% off this week",
        "14. New feature announcement",
        "15. Tutorial: Get started in 3 steps",
        "",
        `_Generated by AI Company OS — ${s.projectName}_`,
        "",
      ].join("\n"),
    },
  ],

  automation_workflow: [
    {
      path: "deliverables/automation/workflow-map.md",
      content: (s) => [
        `# Workflow Map — ${s.projectName}`,
        "",
        `**Session:** ${s.sessionId}`,
        `**Date:** ${formatTimestamp(s.updatedAt)}`,
        "",
        "## Workflow Overview",
        "",
        `**Name:** ${s.projectName}`,
        `**Goal:** ${s.projectIdea.split(".")[0]}`,
        "",
        "## Trigger → Action Flow",
        "",
        "```",
        "TRIGGER",
        "  └─▶ CONDITION CHECK",
        "        ├─▶ [If TRUE] → ACTION A → LOG",
        "        └─▶ [If FALSE] → ACTION B → NOTIFY",
        "```",
        "",
        "## Step Definitions",
        "",
        "| Step | Type | Input | Output | On Error |",
        "|------|------|-------|--------|----------|",
        "| 1. Trigger | Webhook / Cron | Event payload | Validated data | Reject |",
        "| 2. Validate | Condition | Raw input | Parsed fields | Dead letter |",
        "| 3. Transform | Function | Parsed fields | Normalized data | Retry ×3 |",
        "| 4. Execute | API call | Normalized data | Response | Retry ×3 |",
        "| 5. Log | Storage | Response | Log entry | Ignore |",
        "| 6. Notify | Webhook | Log entry | Notification | Ignore |",
        "",
        `_Generated by AI Company OS — ${s.projectName}_`,
        "",
      ].join("\n"),
    },
    {
      path: "deliverables/automation/tools-stack.md",
      content: (s) => [
        `# Tools Stack — ${s.projectName}`,
        "",
        `**Session:** ${s.sessionId}`,
        `**Date:** ${formatTimestamp(s.updatedAt)}`,
        "",
        "## Selected Tools",
        "",
        "| Category | Tool | Purpose | Tier |",
        "|----------|------|---------|------|",
        "| Trigger | Webhook / Cron | Event source | Free |",
        "| Orchestration | N8N / Zapier | Workflow engine | $20/mo |",
        "| Storage | Airtable / Notion | Data persistence | $10/mo |",
        "| Notifications | Slack / Email | Alerting | Free |",
        "| Monitoring | Datadog / Grafana | Observability | $0–$50/mo |",
        "",
        "## Integration Requirements",
        "",
        `**For ${s.projectName}:**`,
        `- ${s.projectIdea}`,
        "",
        "## API Dependencies",
        "",
        "- Auth: API keys stored in secrets manager",
        "- Rate limits: Respect provider limits",
        "- Retries: Exponential backoff on 429/5xx",
        "",
        `_Generated by AI Company OS — ${s.projectName}_`,
        "",
      ].join("\n"),
    },
    {
      path: "deliverables/automation/runbook.md",
      content: (s) => [
        `# Runbook — ${s.projectName}`,
        "",
        `**Session:** ${s.sessionId}`,
        `**Date:** ${formatTimestamp(s.updatedAt)}`,
        "",
        "## Runbook Purpose",
        "",
        `This runbook covers operations for the **${s.projectName}** automation workflow.`,
        "",
        "## Starting the Workflow",
        "",
        "```bash",
        "# Trigger manually",
        "curl -X POST https://your-webhook-url/trigger \\",
        '  -H "Content-Type: application/json" \\',
        "  -d '{\"source\": \"manual\", \"payload\": {}}'",
        "```",
        "",
        "## Monitoring",
        "",
        "| Check | Command / URL | Expected |",
        "|-------|--------------|----------|",
        "| Health | GET /health | 200 OK |",
        "| Logs | Check log stream | No ERROR level |",
        "| Queue | Check dead letter | 0 messages |",
        "",
        "## Troubleshooting",
        "",
        "| Symptom | Likely Cause | Fix |",
        "|---------|-------------|-----|",
        "| Workflow not triggering | Webhook misconfigured | Verify URL and secret |",
        "| Step failing | API down or rate limit | Check status page, retry |",
        "| Data not persisting | Storage quota | Clear old records |",
        "",
        "## Emergency Stop",
        "",
        "1. Disable the trigger (set to inactive)",
        "2. Wait for in-flight steps to complete",
        "3. Clear the queue manually if needed",
        "",
        `_Generated by AI Company OS — ${s.projectName}_`,
        "",
      ].join("\n"),
    },
  ],
};

// ─── Public API ───────────────────────────────────────────────────────────────

/**
 * Generate mission-specific deliverable files in the workspace.
 * Skips saas_project (handled by the existing SaaS scaffold pipeline).
 * Returns relative paths of files written.
 */
export function generateMissionDeliverables(session: AutopilotSession): string[] {
  if (session.missionType === "saas_project") return [];

  const specs = DELIVERABLE_SPECS[session.missionType];
  if (!specs || specs.length === 0) return [];

  const dir = workspaceDir(session.sessionId);
  if (!fs.existsSync(dir)) return [];

  const writtenPaths: string[] = [];

  for (const spec of specs) {
    const fullPath = path.join(dir, spec.path);

    const resolved = path.resolve(fullPath);
    if (!resolved.startsWith(path.resolve(dir))) continue;

    const content = spec.content(session);
    safeWriteFile(fullPath, content);
    writtenPaths.push(spec.path);
  }

  return writtenPaths;
}

/**
 * Check whether mission deliverables have been generated for a session.
 */
export function missionDeliverablesExist(sessionId: string): boolean {
  const dir = workspaceDir(sessionId);
  const delivDir = path.join(dir, "deliverables");
  if (!fs.existsSync(delivDir)) return false;
  try {
    const entries = fs.readdirSync(delivDir, { withFileTypes: true });
    return entries.length > 0;
  } catch {
    return false;
  }
}

/**
 * List all deliverable files for a session (under deliverables/).
 */
export function listMissionDeliverables(sessionId: string): DeliverableFile[] {
  const dir = workspaceDir(sessionId);
  const delivDir = path.join(dir, "deliverables");
  if (!fs.existsSync(delivDir)) return [];

  const files: DeliverableFile[] = [];

  function walk(currentDir: string, relPrefix: string) {
    let entries: fs.Dirent[];
    try {
      entries = fs.readdirSync(currentDir, { withFileTypes: true });
    } catch {
      return;
    }
    for (const entry of entries) {
      const fullPath = path.join(currentDir, entry.name);
      const relPath = relPrefix ? `${relPrefix}/${entry.name}` : entry.name;
      if (entry.isDirectory()) {
        walk(fullPath, relPath);
      } else if (entry.isFile()) {
        try {
          const stat = fs.statSync(fullPath);
          files.push({
            path: `deliverables/${relPath}`,
            name: entry.name,
            size: stat.size,
            modifiedAt: stat.mtime.toISOString(),
          });
        } catch {
          // skip unreadable files
        }
      }
    }
  }

  walk(delivDir, "");
  return files.sort((a, b) => a.path.localeCompare(b.path));
}

/**
 * Read a deliverable file by relative path. Returns null if not found.
 */
export function readDeliverableFile(sessionId: string, relativePath: string): string | null {
  const dir = workspaceDir(sessionId);
  const filePath = path.join(dir, relativePath);

  const resolved = path.resolve(filePath);
  if (!resolved.startsWith(path.resolve(dir))) return null;
  if (!fs.existsSync(filePath)) return null;

  try {
    return fs.readFileSync(filePath, "utf-8");
  } catch {
    return null;
  }
}
