import fs from "fs";
import path from "path";
import type { AutopilotPhase, AutopilotSession, AutopilotTask, AutopilotLog } from "./autopilotStore";
import { AUTOPILOT_PHASES } from "./autopilotStore";
import { validateGeneratedProject } from "./projectValidator";

// ─── Paths ──────────────────────────────────────────────────────────────────

const REPO_ROOT = path.resolve(process.cwd(), "..");
const WORKSPACES_ROOT = path.join(REPO_ROOT, "generated", "autopilot-workspaces");

function workspaceDir(sessionId: string): string {
  return path.join(WORKSPACES_ROOT, sessionId);
}

// ─── Types ──────────────────────────────────────────────────────────────────────

export interface WorkspaceFile {
  path: string;
  name: string;
  size: number;
  modifiedAt: string;
}

export interface WorkspaceSummary {
  sessionId: string;
  projectName: string;
  exists: boolean;
  fileCount: number;
  totalSize: number;
  files: WorkspaceFile[];
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function ensureDir(dir: string) {
  fs.mkdirSync(dir, { recursive: true });
}

function safeWriteFile(filePath: string, content: string) {
  ensureDir(path.dirname(filePath));
  fs.writeFileSync(filePath, content, "utf-8");
}

function formatTimestamp(iso: string): string {
  try {
    return new Date(iso).toISOString().replace("T", " ").slice(0, 19);
  } catch {
    return iso;
  }
}

const PHASE_FILE_MAP: Record<AutopilotPhase, string> = {
  idea:         "phases/01-idea-analysis.md",
  planning:     "phases/02-product-definition.md",
  architecture: "phases/03-architecture.md",
  frontend:     "phases/04-frontend-design.md",
  backend:      "phases/05-backend-implementation.md",
  validation:   "phases/06-validation.md",
  build:        "phases/07-build-preparation.md",
  runtime:      "phases/08-runtime-monitoring.md",
};

// ─── Public API ───────────────────────────────────────────────────────────────

/**
 * Create the workspace directory and initial files for a session.
 * Called at session creation or on first run-step if workspace missing.
 */
export function createWorkspaceForSession(session: AutopilotSession): void {
  const dir = workspaceDir(session.sessionId);
  ensureDir(dir);

  // README.md
  safeWriteFile(path.join(dir, "README.md"), [
    `# ${session.projectName}`,
    "",
    `> ${session.projectIdea}`,
    "",
    `**Session:** ${session.sessionId}`,
    `**Template:** ${session.template ?? "custom"}`,
    `**Stack:** ${session.stack ?? "nextjs-prisma"}`,
    `**Created:** ${formatTimestamp(session.createdAt)}`,
    `**Provider:** NVIDIA API (Nemotron)`,
    "",
    "This workspace was generated by AI Company OS Autopilot.",
    "",
  ].join("\n"));

  // roadmap.md
  safeWriteFile(path.join(dir, "roadmap.md"), [
    `# Roadmap — ${session.projectName}`,
    "",
    ...session.roadmap.map((step, i) => `${i + 1}. ${step}`),
    "",
  ].join("\n"));

  // tasks.json
  safeWriteFile(path.join(dir, "tasks.json"), JSON.stringify(session.tasks, null, 2) + "\n");

  // logs.md
  safeWriteFile(path.join(dir, "logs.md"), [
    `# Autopilot Logs — ${session.projectName}`,
    "",
    formatLogEntries(session.logs),
    "",
  ].join("\n"));

  // Phase files: create initial stubs
  ensureDir(path.join(dir, "phases"));
  for (const phase of AUTOPILOT_PHASES) {
    const phaseFile = path.join(dir, PHASE_FILE_MAP[phase.id]);
    if (!fs.existsSync(phaseFile)) {
      safeWriteFile(phaseFile, [
        `# ${phase.label}`,
        "",
        `**Agent:** ${phase.agent}`,
        `**Provider:** NVIDIA API`,
        "",
        "_This file will be populated as the autopilot progresses through this phase._",
        "",
      ].join("\n"));
    }
  }
}

/**
 * Write or update a file in the workspace.
 */
export function writeWorkspaceFile(sessionId: string, relativePath: string, content: string): boolean {
  const dir = workspaceDir(sessionId);
  const filePath = path.join(dir, relativePath);

  // Prevent path traversal
  const resolved = path.resolve(filePath);
  if (!resolved.startsWith(path.resolve(dir))) return false;

  safeWriteFile(filePath, content);
  return true;
}

/**
 * Read a file from the workspace. Returns null if not found.
 */
export function readWorkspaceFile(sessionId: string, relativePath: string): string | null {
  const dir = workspaceDir(sessionId);
  const filePath = path.join(dir, relativePath);

  const resolved = path.resolve(filePath);
  if (!resolved.startsWith(path.resolve(dir))) return null;

  if (!fs.existsSync(filePath)) return null;
  try {
    return fs.readFileSync(filePath, "utf-8");
  } catch {
    return null;
  }
}

/**
 * List all files in the workspace.
 */
export function listWorkspaceFiles(sessionId: string): WorkspaceFile[] {
  const dir = workspaceDir(sessionId);
  if (!fs.existsSync(dir)) return [];

  const files: WorkspaceFile[] = [];

  function walk(currentDir: string, prefix: string) {
    const entries = fs.readdirSync(currentDir, { withFileTypes: true });
    for (const entry of entries) {
      const fullPath = path.join(currentDir, entry.name);
      const relPath = prefix ? `${prefix}/${entry.name}` : entry.name;
      if (entry.isDirectory()) {
        walk(fullPath, relPath);
      } else if (entry.isFile()) {
        try {
          const stat = fs.statSync(fullPath);
          files.push({
            path: relPath,
            name: entry.name,
            size: stat.size,
            modifiedAt: stat.mtime.toISOString(),
          });
        } catch {
          // skip unreadable files
        }
      }
    }
  }

  walk(dir, "");
  return files.sort((a, b) => a.path.localeCompare(b.path));
}

/**
 * Get a summary of the workspace.
 */
export function getWorkspaceSummary(sessionId: string): WorkspaceSummary {
  const dir = workspaceDir(sessionId);
  const exists = fs.existsSync(dir);
  const files = exists ? listWorkspaceFiles(sessionId) : [];
  const totalSize = files.reduce((sum, f) => sum + f.size, 0);

  let projectName = sessionId;
  if (exists) {
    const readmePath = path.join(dir, "README.md");
    if (fs.existsSync(readmePath)) {
      try {
        const firstLine = fs.readFileSync(readmePath, "utf-8").split("\n")[0] ?? "";
        const match = firstLine.match(/^#\s+(.+)$/);
        if (match) projectName = match[1];
      } catch {
        // ignore
      }
    }
  }

  return { sessionId, projectName, exists, fileCount: files.length, totalSize, files };
}

/**
 * Update workspace files after a run-step completes.
 * - Update tasks.json
 * - Append to logs.md
 * - Update the phase file if the task completed
 */
export function updateWorkspaceAfterStep(
  sessionId: string,
  tasks: AutopilotTask[],
  logs: AutopilotLog[],
  completedTask: AutopilotTask | null,
): void {
  const dir = workspaceDir(sessionId);
  if (!fs.existsSync(dir)) return;

  // Update tasks.json
  safeWriteFile(path.join(dir, "tasks.json"), JSON.stringify(tasks, null, 2) + "\n");

  // Update logs.md
  safeWriteFile(path.join(dir, "logs.md"), [
    `# Autopilot Logs`,
    "",
    formatLogEntries(logs),
    "",
  ].join("\n"));

  // Update phase file for the completed task
  if (completedTask && completedTask.status === "completed") {
    const phaseFile = PHASE_FILE_MAP[completedTask.phase as AutopilotPhase];
    if (phaseFile) {
      const phaseInfo = AUTOPILOT_PHASES.find((p) => p.id === completedTask.phase);
      const phaseTasks = tasks.filter((t) => t.phase === completedTask.phase);

      safeWriteFile(path.join(dir, phaseFile), [
        `# ${phaseInfo?.label ?? completedTask.phase}`,
        "",
        `**Agent:** ${completedTask.agent}`,
        `**Provider:** NVIDIA API`,
        `**Last updated:** ${formatTimestamp(completedTask.updatedAt)}`,
        "",
        "## Tasks",
        "",
        ...phaseTasks.map((t) => `- [${t.status === "completed" ? "x" : " "}] ${t.title} (${t.agent})`),
        "",
        "## Output",
        "",
        `Task **${completedTask.title}** completed by ${completedTask.agent}.`,
        "",
        `Description: ${completedTask.description}`,
        "",
        `_Generated by AI Company OS Autopilot — NVIDIA API_`,
        "",
      ].join("\n"));
    }
  }
}

// ─── Agent Artifact Definitions ────────────────────────────────────────────

const AGENT_ARTIFACTS: Record<string, { dir: string; files: { name: string; title: string; sections: (session: AutopilotSession, task: AutopilotTask) => string[] }[] }> = {
  product_agent: {
    dir: "product",
    files: [
      {
        name: "brief.md",
        title: "Product Brief",
        sections: (session, task) => [
          `# Product Brief — ${session.projectName}`,
          "",
          `**Session:** ${session.sessionId}`,
          `**Task:** ${task.id} — ${task.title}`,
          `**Agent:** product_agent`,
          `**Date:** ${formatTimestamp(task.updatedAt)}`,
          "",
          "## Objectives",
          "",
          `- ${task.description}`,
          `- Define ICP, value proposition and competitive positioning for ${session.projectName}`,
          `- Align product vision with market needs`,
          "",
          "## Key Decisions",
          "",
          `- Target market: early-adopter SaaS users seeking automation`,
          `- Core value prop: AI-driven workflow automation`,
          `- Differentiation: autonomous multi-agent orchestration`,
          `- MVP scope defined per roadmap priorities`,
          "",
          "## Next Actions",
          "",
          "- Validate user stories with target personas",
          "- Prioritize features for MVP release",
          "- Map customer journey and onboarding flow",
          "",
          `_Generated by AI Company OS Autopilot — NVIDIA API_`,
          "",
        ],
      },
      {
        name: "user-stories.md",
        title: "User Stories",
        sections: (session, task) => [
          `# User Stories — ${session.projectName}`,
          "",
          `**Session:** ${session.sessionId}`,
          `**Task:** ${task.id} — ${task.title}`,
          `**Agent:** product_agent`,
          `**Date:** ${formatTimestamp(task.updatedAt)}`,
          "",
          "## Core Stories",
          "",
          `1. **As a** user, **I want to** launch an autopilot session, **so that** I can build my product autonomously.`,
          `2. **As a** user, **I want to** monitor agent progress in real-time, **so that** I can stay informed without manual checking.`,
          `3. **As a** user, **I want to** review generated artifacts, **so that** I can validate quality and provide feedback.`,
          `4. **As a** user, **I want to** pause/resume execution, **so that** I retain control over the build process.`,
          `5. **As a** user, **I want to** see workspace files organized by agent, **so that** I can quickly find deliverables.`,
          "",
          "## Acceptance Criteria",
          "",
          "- Autopilot completes full 8-phase cycle",
          "- Each agent produces at least one artifact",
          "- User can view real-time logs and progress",
          "",
          `_Generated by AI Company OS Autopilot — NVIDIA API_`,
          "",
        ],
      },
    ],
  },
  architect_agent: {
    dir: "architecture",
    files: [
      {
        name: "system-design.md",
        title: "System Design",
        sections: (session, task) => [
          `# System Design — ${session.projectName}`,
          "",
          `**Session:** ${session.sessionId}`,
          `**Task:** ${task.id} — ${task.title}`,
          `**Agent:** architect_agent`,
          `**Date:** ${formatTimestamp(task.updatedAt)}`,
          "",
          "## Objectives",
          "",
          `- ${task.description}`,
          `- Define modular architecture with clear boundaries`,
          `- Ensure scalability and maintainability`,
          "",
          "## Architecture Overview",
          "",
          "```",
          "┌──────────────┐     ┌──────────────┐     ┌──────────────┐",
          "│   Frontend   │────▶│   API Layer   │────▶│   Database    │",
          "│  (Next.js)   │     │  (REST/WS)    │     │  (Postgres)   │",
          "└──────────────┘     └──────────────┘     └──────────────┘",
          "       │                    │                     │",
          "       ▼                    ▼                     ▼",
          "  UI Components      Business Logic         Data Models",
          "  Design System       Services              Migrations",
          "```",
          "",
          "## Key Decisions",
          "",
          `- Stack: ${session.stack ?? "nextjs-prisma"}`,
          "- Module boundaries: frontend / API / data layers",
          "- API pattern: REST with WebSocket for real-time events",
          "- Auth: JWT with refresh token rotation",
          "",
          "## Next Actions",
          "",
          "- Finalize data model and API surface",
          "- Define service contracts between modules",
          "- Document integration patterns",
          "",
          `_Generated by AI Company OS Autopilot — NVIDIA API_`,
          "",
        ],
      },
      {
        name: "data-model.md",
        title: "Data Model",
        sections: (session, task) => [
          `# Data Model — ${session.projectName}`,
          "",
          `**Session:** ${session.sessionId}`,
          `**Task:** ${task.id} — ${task.title}`,
          `**Agent:** architect_agent`,
          `**Date:** ${formatTimestamp(task.updatedAt)}`,
          "",
          "## Objectives",
          "",
          `- ${task.description}`,
          "- Design normalized schema with clear relationships",
          "",
          "## Core Entities",
          "",
          "```prisma",
          "model User {",
          "  id        String   @id @default(cuid())",
          "  email     String   @unique",
          "  name      String?",
          "  role      Role     @default(USER)",
          "  createdAt DateTime @default(now())",
          "}",
          "",
          "model Project {",
          "  id          String   @id @default(cuid())",
          "  name        String",
          "  description String?",
          "  ownerId     String",
          "  owner       User     @relation(fields: [ownerId], references: [id])",
          "  createdAt   DateTime @default(now())",
          "}",
          "",
          "enum Role { USER ADMIN }",
          "```",
          "",
          "## Key Decisions",
          "",
          "- UUID-based primary keys (cuid)",
          "- Soft delete via status fields",
          "- Audit trail via createdAt/updatedAt",
          "",
          "## Next Actions",
          "",
          "- Implement Prisma migrations",
          "- Add seed data for development",
          "- Define API DTOs matching models",
          "",
          `_Generated by AI Company OS Autopilot — NVIDIA API_`,
          "",
        ],
      },
    ],
  },
  frontend_agent: {
    dir: "frontend",
    files: [
      {
        name: "ui-plan.md",
        title: "UI Plan",
        sections: (session, task) => [
          `# UI Plan — ${session.projectName}`,
          "",
          `**Session:** ${session.sessionId}`,
          `**Task:** ${task.id} — ${task.title}`,
          `**Agent:** frontend_agent`,
          `**Date:** ${formatTimestamp(task.updatedAt)}`,
          "",
          "## Objectives",
          "",
          `- ${task.description}`,
          "- Design responsive, accessible UI with consistent design system",
          "",
          "## Pages & Components",
          "",
          "| Page | Components | Priority |",
          "|------|-----------|----------|",
          "| Dashboard | Stats, Charts, Activity Feed | P0 |",
          "| Onboarding | Step Wizard, Progress Bar | P0 |",
          "| Settings | Form, Toggle, Select | P1 |",
          "| Workspace | FileTree, Preview, Editor | P1 |",
          "",
          "## Design System",
          "",
          "- Colors: dark theme with accent highlights",
          "- Typography: system font stack (ui-monospace, sans-serif)",
          "- Spacing: 4px base unit",
          "- Components: Button, Card, Badge, Modal, Toast",
          "",
          "## Key Decisions",
          "",
          "- Dark-first design with accent colors",
          "- Responsive grid layout (mobile-friendly)",
          "- Component library built in-house",
          "",
          "## Next Actions",
          "",
          "- Build component library foundations",
          "- Implement dashboard layout",
          "- Add animations and transitions",
          "",
          `_Generated by AI Company OS Autopilot — NVIDIA API_`,
          "",
        ],
      },
      {
        name: "routes.md",
        title: "Routes & Navigation",
        sections: (session, task) => [
          `# Routes & Navigation — ${session.projectName}`,
          "",
          `**Session:** ${session.sessionId}`,
          `**Task:** ${task.id} — ${task.title}`,
          `**Agent:** frontend_agent`,
          `**Date:** ${formatTimestamp(task.updatedAt)}`,
          "",
          "## Route Map",
          "",
          "| Route | Page | Auth |",
          "|-------|------|------|",
          "| `/` | Landing | No |",
          "| `/dashboard` | Dashboard | Yes |",
          "| `/projects` | Project List | Yes |",
          "| `/projects/new` | Create Project | Yes |",
          "| `/settings` | Settings | Yes |",
          "| `/autopilot` | Autopilot Sessions | Yes |",
          "| `/autopilot/[id]` | Session Detail | Yes |",
          "",
          "## Navigation Structure",
          "",
          "- Sidebar: Dashboard, Projects, Autopilot, Logs, Settings",
          "- Breadcrumbs: contextual navigation per page",
          "- Quick actions: header-level shortcuts",
          "",
          "## Key Decisions",
          "",
          "- Next.js App Router with server components",
          "- Client-side navigation with Next Link",
          "- Protected routes via middleware",
          "",
          "## Next Actions",
          "",
          "- Implement route guards",
          "- Build sidebar navigation",
          "- Add page transition animations",
          "",
          `_Generated by AI Company OS Autopilot — NVIDIA API_`,
          "",
        ],
      },
    ],
  },
  backend_agent: {
    dir: "backend",
    files: [
      {
        name: "api-plan.md",
        title: "API Plan",
        sections: (session, task) => [
          `# API Plan — ${session.projectName}`,
          "",
          `**Session:** ${session.sessionId}`,
          `**Task:** ${task.id} — ${task.title}`,
          `**Agent:** backend_agent`,
          `**Date:** ${formatTimestamp(task.updatedAt)}`,
          "",
          "## Objectives",
          "",
          `- ${task.description}`,
          "- Design RESTful API with consistent patterns",
          "",
          "## API Endpoints",
          "",
          "| Method | Path | Description | Auth |",
          "|--------|------|-------------|------|",
          "| POST | /api/auth/login | Login | No |",
          "| POST | /api/auth/register | Register | No |",
          "| GET | /api/projects | List projects | Yes |",
          "| POST | /api/projects | Create project | Yes |",
          "| GET | /api/projects/:id | Get project | Yes |",
          "| GET | /api/autopilot/sessions | List sessions | Yes |",
          "| POST | /api/autopilot/sessions | Create session | Yes |",
          "| POST | /api/autopilot/sessions/:id/run-step | Run step | Yes |",
          "",
          "## Key Decisions",
          "",
          "- RESTful pattern with consistent response shape",
          "- JWT auth with refresh tokens",
          "- Rate limiting: 100 req/min per user",
          "- Error format: { ok: false, message: string }",
          "",
          "## Next Actions",
          "",
          "- Implement auth middleware",
          "- Build CRUD routes for core entities",
          "- Add request validation schemas",
          "",
          `_Generated by AI Company OS Autopilot — NVIDIA API_`,
          "",
        ],
      },
      {
        name: "services.md",
        title: "Services Layer",
        sections: (session, task) => [
          `# Services Layer — ${session.projectName}`,
          "",
          `**Session:** ${session.sessionId}`,
          `**Task:** ${task.id} — ${task.title}`,
          `**Agent:** backend_agent`,
          `**Date:** ${formatTimestamp(task.updatedAt)}`,
          "",
          "## Objectives",
          "",
          `- ${task.description}`,
          "- Define business logic services with clear contracts",
          "",
          "## Services",
          "",
          "### AuthService",
          "- login(email, password) → { token, refreshToken }",
          "- register(data) → User",
          "- verifyToken(token) → Payload",
          "",
          "### ProjectService",
          "- list(userId) → Project[]",
          "- create(data) → Project",
          "- getById(id) → Project | null",
          "",
          "### AutopilotService",
          "- createSession(input) → Session",
          "- runStep(sessionId) → RunStepResult",
          "- runAll(sessionId) → RunAllResult",
          "",
          "## Key Decisions",
          "",
          "- Service layer pattern (controller → service → repo)",
          "- Dependency injection for testability",
          "- Transactional writes for data integrity",
          "",
          "## Next Actions",
          "",
          "- Implement service interfaces",
          "- Add unit tests for core logic",
          "- Wire services to API routes",
          "",
          `_Generated by AI Company OS Autopilot — NVIDIA API_`,
          "",
        ],
      },
    ],
  },
  qa_agent: {
    dir: "qa",
    files: [
      {
        name: "test-plan.md",
        title: "Test Plan",
        sections: (session, task) => [
          `# Test Plan — ${session.projectName}`,
          "",
          `**Session:** ${session.sessionId}`,
          `**Task:** ${task.id} — ${task.title}`,
          `**Agent:** qa_agent`,
          `**Date:** ${formatTimestamp(task.updatedAt)}`,
          "",
          "## Objectives",
          "",
          `- ${task.description}`,
          "- Ensure comprehensive test coverage across all layers",
          "",
          "## Test Matrix",
          "",
          "| Layer | Type | Count | Coverage |",
          "|-------|------|-------|----------|",
          "| Unit | Service logic | 20+ | >80% |",
          "| Integration | API routes | 15+ | >70% |",
          "| E2E | Critical flows | 5+ | 100% smoke |",
          "| Contract | API shape | 10+ | All endpoints |",
          "",
          "## Test Categories",
          "",
          "1. **Unit Tests** — services, stores, helpers",
          "2. **Integration Tests** — API routes with mocked DB",
          "3. **Smoke Tests** — build succeeds, pages render",
          "4. **Security Tests** — auth, path traversal, XSS",
          "",
          "## Key Decisions",
          "",
          "- Vitest for unit/integration",
          "- React Testing Library for component tests",
          "- Deterministic test data via factories",
          "",
          "## Next Actions",
          "",
          "- Write unit test suite for core stores",
          "- Add integration tests for API routes",
          "- Set up CI test pipeline",
          "",
          `_Generated by AI Company OS Autopilot — NVIDIA API_`,
          "",
        ],
      },
      {
        name: "risks.md",
        title: "Risks & Mitigations",
        sections: (session, task) => [
          `# Risks & Mitigations — ${session.projectName}`,
          "",
          `**Session:** ${session.sessionId}`,
          `**Task:** ${task.id} — ${task.title}`,
          `**Agent:** qa_agent`,
          `**Date:** ${formatTimestamp(task.updatedAt)}`,
          "",
          "## Identified Risks",
          "",
          "| # | Risk | Severity | Likelihood | Mitigation |",
          "|---|------|----------|------------|------------|",
          "| 1 | NVIDIA API downtime | High | Low | Fallback to local simulation |",
          "| 2 | Data loss on session crash | High | Medium | JSON persistence + workspace backup |",
          "| 3 | Path traversal in workspace | High | Low | Resolved path validation |",
          "| 4 | Race condition on concurrent run-step | Medium | Medium | Session status lock |",
          "| 5 | Stale workspace files | Low | Medium | Auto-refresh on each step |",
          "",
          "## Security Considerations",
          "",
          "- API keys never logged or written to workspace",
          "- Path traversal protected on all file operations",
          "- Input validation on all API endpoints",
          "",
          "## Key Decisions",
          "",
          "- Fail-safe defaults: all writes validated",
          "- Rate-limited execution to prevent resource exhaustion",
          "- Workspace files are read-only for agents",
          "",
          "## Next Actions",
          "",
          "- Run vulnerability scan on dependencies",
          "- Add security-focused integration tests",
          "- Verify all error paths have safe fallbacks",
          "",
          `_Generated by AI Company OS Autopilot — NVIDIA API_`,
          "",
        ],
      },
    ],
  },
  devops_agent: {
    dir: "devops",
    files: [
      {
        name: "deployment-plan.md",
        title: "Deployment Plan",
        sections: (session, task) => [
          `# Deployment Plan — ${session.projectName}`,
          "",
          `**Session:** ${session.sessionId}`,
          `**Task:** ${task.id} — ${task.title}`,
          `**Agent:** devops_agent`,
          `**Date:** ${formatTimestamp(task.updatedAt)}`,
          "",
          "## Objectives",
          "",
          `- ${task.description}`,
          "- Define reliable deployment workflow with rollback capability",
          "",
          "## Deployment Strategy",
          "",
          "| Stage | Environment | Trigger |",
          "|-------|-------------|---------|",
          "| Build | CI runner | Push to main |",
          "| Test | CI runner | After build |",
          "| Staging | staging.example.com | After test pass |",
          "| Production | example.com | Manual approval |",
          "",
          "## Infrastructure",
          "",
          "- Hosting: Vercel (frontend) + Railway (backend)",
          "- Database: managed PostgreSQL",
          "- CI/CD: GitHub Actions",
          "- Monitoring: built-in runtime health checks",
          "",
          "## Key Decisions",
          "",
          "- Blue-green deployment for zero downtime",
          "- Feature flags for progressive rollout",
          "- Automated rollback on health check failure",
          "",
          "## Next Actions",
          "",
          "- Set up GitHub Actions workflow",
          "- Configure staging environment",
          "- Implement health check endpoint",
          "",
          `_Generated by AI Company OS Autopilot — NVIDIA API_`,
          "",
        ],
      },
      {
        name: "env-checklist.md",
        title: "Environment Checklist",
        sections: (session, task) => [
          `# Environment Checklist — ${session.projectName}`,
          "",
          `**Session:** ${session.sessionId}`,
          `**Task:** ${task.id} — ${task.title}`,
          `**Agent:** devops_agent`,
          `**Date:** ${formatTimestamp(task.updatedAt)}`,
          "",
          "## Required Environment Variables",
          "",
          "| Variable | Purpose | Required |",
          "|----------|---------|----------|",
          "| DATABASE_URL | Database connection | Yes |",
          "| NVIDIA_API_KEY | AI inference provider | Yes |",
          "| NEXTAUTH_SECRET | Auth encryption | Yes |",
          "| NODE_ENV | Runtime mode | Yes |",
          "",
          "## Pre-Deployment Checklist",
          "",
          "- [ ] All environment variables set",
          "- [ ] Database migrations applied",
          "- [ ] Build succeeds (`npm run build`)",
          "- [ ] Tests pass (`npm test`)",
          "- [ ] No secrets in source code",
          "- [ ] Health check endpoint responds",
          "- [ ] SSL certificate valid",
          "",
          "## Key Decisions",
          "",
          "- Secrets via environment variables only",
          "- .env.example committed, .env ignored",
          "- Runtime health monitoring on /api/runtime/status",
          "",
          "## Next Actions",
          "",
          "- Verify all env vars in staging",
          "- Run full smoke test suite",
          "- Confirm monitoring alerts are active",
          "",
          `_Generated by AI Company OS Autopilot — NVIDIA API_`,
          "",
        ],
      },
    ],
  },
};

/**
 * Generate or update agent artifact files in the workspace.
 * Returns an array of relative paths for the files that were written.
 */
export function generateAgentArtifact(session: AutopilotSession, task: AutopilotTask): string[] {
  const config = AGENT_ARTIFACTS[task.agent];
  if (!config) return [];

  const dir = workspaceDir(session.sessionId);
  if (!fs.existsSync(dir)) return [];

  const artifactDir = path.join(dir, config.dir);
  ensureDir(artifactDir);

  const writtenPaths: string[] = [];

  for (const file of config.files) {
    const relPath = `${config.dir}/${file.name}`;
    const fullPath = path.join(dir, relPath);

    // Prevent path traversal
    const resolved = path.resolve(fullPath);
    if (!resolved.startsWith(path.resolve(dir))) continue;

    const content = file.sections(session, task).join("\n");
    safeWriteFile(fullPath, content);
    writtenPaths.push(relPath);
  }

  return writtenPaths;
}

// ─── Project Scaffold Generator ──────────────────────────────────────────────

const SCAFFOLD_FILES: { path: string; content: (ctx: ScaffoldContext) => string }[] = [
  {
    path: "project/package.json",
    content: (ctx) => JSON.stringify({
      name: ctx.slug,
      version: "0.1.0",
      private: true,
      scripts: {
        dev: "next dev",
        build: "next build",
        start: "next start",
        lint: "next lint",
      },
      dependencies: {
        next: "14.2.29",
        react: "^18",
        "react-dom": "^18",
      },
      devDependencies: {
        typescript: "^5",
        "@types/node": "^20",
        "@types/react": "^18",
        "@types/react-dom": "^18",
        autoprefixer: "^10",
        postcss: "^8",
        tailwindcss: "^3",
      },
    }, null, 2) + "\n",
  },
  {
    path: "project/README.md",
    content: (ctx) => [
      `# ${ctx.name}`,
      "",
      `> ${ctx.slogan}`,
      "",
      `**Session:** ${ctx.sessionId}`,
      `**Target:** ${ctx.audience}`,
      `**Generated:** ${ctx.date}`,
      "",
      "## Features",
      "",
      ...ctx.features.map((f) => `- ${f}`),
      "",
      "## Getting Started",
      "",
      "```bash",
      "cd project",
      "npm install",
      "npm run dev",
      "```",
      "",
      "Open [http://localhost:3000](http://localhost:3000) in your browser.",
      "",
      `_Generated by AI Company OS Autopilot_`,
      "",
    ].join("\n"),
  },
  {
    path: "project/app/layout.tsx",
    content: (ctx) => [
      `import type { Metadata } from "next";`,
      `import "./globals.css";`,
      "",
      `export const metadata: Metadata = {`,
      `  title: "${ctx.name}",`,
      `  description: "${ctx.slogan}",`,
      `};`,
      "",
      `export default function RootLayout({`,
      `  children,`,
      `}: {`,
      `  children: React.ReactNode;`,
      `}) {`,
      `  return (`,
      `    <html lang="en" className="dark">`,
      `      <body className="bg-gray-950 text-gray-100 antialiased">{children}</body>`,
      `    </html>`,
      `  );`,
      `}`,
      "",
    ].join("\n"),
  },
  {
    path: "project/app/globals.css",
    content: () => [
      `@tailwind base;`,
      `@tailwind components;`,
      `@tailwind utilities;`,
      "",
      `:root {`,
      `  --accent: #6366f1;`,
      `  --accent-light: #818cf8;`,
      `}`,
      "",
      `body {`,
      `  font-feature-settings: "rlig" 1, "calt" 1;`,
      `}`,
      "",
    ].join("\n"),
  },
  {
    path: "project/app/page.tsx",
    content: (ctx) => [
      `import Hero from "@/components/Hero";`,
      `import Pricing from "@/components/Pricing";`,
      `import DashboardPreview from "@/components/DashboardPreview";`,
      "",
      `export default function Home() {`,
      `  return (`,
      `    <main className="min-h-screen">`,
      `      <Hero />`,
      `      <DashboardPreview />`,
      `      <Pricing />`,
      `      <footer className="border-t border-gray-800 py-8 text-center text-sm text-gray-500">`,
      `        <p>&copy; {new Date().getFullYear()} ${ctx.name}. All rights reserved.</p>`,
      `      </footer>`,
      `    </main>`,
      `  );`,
      `}`,
      "",
    ].join("\n"),
  },
  {
    path: "project/lib/config.ts",
    content: (ctx) => [
      `export const APP_NAME = "${ctx.name}";`,
      `export const APP_SLUG = "${ctx.slug}";`,
      `export const APP_SLOGAN = "${ctx.slogan}";`,
      `export const APP_AUDIENCE = "${ctx.audience}";`,
      "",
      `export const FEATURES = [`,
      ...ctx.features.map((f) => `  "${f}",`),
      `] as const;`,
      "",
      `export const PRICING_TIERS = [`,
      ...ctx.pricing.map((t) => `  { name: "${t.name}", price: "${t.price}", features: [${t.features.map((f) => `"${f}"`).join(", ")}] },`),
      `] as const;`,
      "",
      `export const SUGGESTED_ROUTES = [`,
      ...ctx.routes.map((r) => `  { path: "${r.path}", label: "${r.label}" },`),
      `] as const;`,
      "",
    ].join("\n"),
  },
  {
    path: "project/components/Hero.tsx",
    content: (ctx) => [
      `import { APP_NAME, APP_SLOGAN } from "@/lib/config";`,
      "",
      `export default function Hero() {`,
      `  return (`,
      `    <section className="relative overflow-hidden py-20 px-6 text-center">`,
      `      <div className="absolute inset-0 bg-gradient-to-b from-indigo-600/10 to-transparent" />`,
      `      <div className="relative mx-auto max-w-3xl">`,
      `        <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-6xl">`,
      `          {APP_NAME}`,
      `        </h1>`,
      `        <p className="mt-6 text-lg leading-8 text-gray-300">`,
      `          {APP_SLOGAN}`,
      `        </p>`,
      `        <div className="mt-10 flex items-center justify-center gap-x-6">`,
      `          <a`,
      `            href="/dashboard"`,
      `            className="rounded-md bg-indigo-600 px-6 py-3 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 transition-colors"`,
      `          >`,
      `            Get Started`,
      `          </a>`,
      `          <a`,
      `            href="#features"`,
      `            className="text-sm font-semibold leading-6 text-gray-300 hover:text-white transition-colors"`,
      `          >`,
      `            Learn more &rarr;`,
      `          </a>`,
      `        </div>`,
      `        <div id="features" className="mt-16 grid grid-cols-1 gap-6 sm:grid-cols-3">`,
      ...ctx.features.slice(0, 3).map((f) => [
        `          <div key="${f}" className="rounded-xl border border-gray-800 bg-gray-900/50 p-6 text-left">`,
        `            <h3 className="font-semibold text-white">${f}</h3>`,
        `            <p className="mt-2 text-sm text-gray-400">Streamlined ${f.toLowerCase()} for modern teams.</p>`,
        `          </div>`,
      ].join("\n")),
        `        </div>`,
      `      </div>`,
      `    </section>`,
      `  );`,
      `}`,
      "",
    ].join("\n"),
  },
  {
    path: "project/components/Pricing.tsx",
    content: (ctx) => [
      `import { PRICING_TIERS } from "@/lib/config";`,
      "",
      `export default function Pricing() {`,
      `  return (`,
      `    <section className="py-20 px-6">`,
      `      <div className="mx-auto max-w-5xl">`,
      `        <h2 className="text-center text-3xl font-bold tracking-tight text-white sm:text-4xl">`,
      `          Simple pricing`,
      `        </h2>`,
      `        <p className="mt-4 text-center text-gray-400">`,
      `          Start free. Scale when you are ready.`,
      `        </p>`,
      `        <div className="mt-12 grid grid-cols-1 gap-8 sm:grid-cols-${Math.min(ctx.pricing.length, 3)}">`,
      `          {PRICING_TIERS.map((tier) => (`,
      `            <div`,
      `              key={tier.name}`,
      `              className="rounded-2xl border border-gray-800 bg-gray-900/50 p-8"`,
      `            >`,
      `              <h3 className="text-lg font-semibold text-white">{tier.name}</h3>`,
      `              <p className="mt-4 text-4xl font-extrabold text-white">{tier.price}</p>`,
      `              <ul className="mt-8 space-y-3">`,
      `                {tier.features.map((f) => (`,
      `                  <li key={f} className="flex items-center gap-2 text-sm text-gray-300">`,
      `                    <span className="text-indigo-400">&#10003;</span> {f}`,
      `                  </li>`,
      `                ))}`,
      `              </ul>`,
      `            </div>`,
      `          ))}`,
      `        </div>`,
      `      </div>`,
      `    </section>`,
      `  );`,
      `}`,
      "",
    ].join("\n"),
  },
  {
    path: "project/components/DashboardPreview.tsx",
    content: (ctx) => [
      `import { APP_NAME } from "@/lib/config";`,
      "",
      `export default function DashboardPreview() {`,
      `  return (`,
      `    <section className="py-20 px-6 bg-gray-900/30">`,
      `      <div className="mx-auto max-w-5xl">`,
      `        <h2 className="text-center text-3xl font-bold tracking-tight text-white sm:text-4xl">`,
      `          Powerful dashboard`,
      `        </h2>`,
      `        <p className="mt-4 text-center text-gray-400">`,
      `          Everything you need to manage your {APP_NAME.toLowerCase()} workflow.`,
      `        </p>`,
      `        <div className="mt-12 overflow-hidden rounded-xl border border-gray-800 bg-gray-950 shadow-2xl">`,
      `          <div className="flex items-center gap-2 border-b border-gray-800 px-4 py-3">`,
      `            <div className="h-3 w-3 rounded-full bg-red-500/60" />`,
      `            <div className="h-3 w-3 rounded-full bg-yellow-500/60" />`,
      `            <div className="h-3 w-3 rounded-full bg-green-500/60" />`,
      `            <span className="ml-3 text-xs text-gray-500">${ctx.slug} — Dashboard</span>`,
      `          </div>`,
      `          <div className="grid grid-cols-4 gap-4 p-6">`,
      `            <div className="col-span-1 space-y-2">`,
      `              {[${ctx.routes.slice(0, 5).map((r) => `"${r.label}"`).join(", ")}].map((item) => (`,
      `                <div key={item} className="rounded-lg bg-gray-900 px-3 py-2 text-sm text-gray-400">{item}</div>`,
      `              ))}`,
      `            </div>`,
      `            <div className="col-span-3 space-y-4">`,
      `              <div className="grid grid-cols-3 gap-3">`,
      `                {["Active", "Completed", "Pending"].map((label) => (`,
      `                  <div key={label} className="rounded-lg border border-gray-800 bg-gray-900 p-4">`,
      `                    <div className="text-xs text-gray-500">{label}</div>`,
      `                    <div className="mt-1 text-2xl font-bold text-white">`,
      `                      {Math.floor(Math.random() * 100)}`,
      `                    </div>`,
      `                  </div>`,
      `                ))}`,
      `              </div>`,
      `              <div className="h-32 rounded-lg border border-gray-800 bg-gray-900 p-4">`,
      `                <div className="text-xs font-medium text-gray-500">Activity</div>`,
      `                <div className="mt-4 flex items-end gap-1 h-16">`,
      `                  {Array.from({ length: 14 }).map((_, i) => (`,
      `                    <div`,
      `                      key={i}`,
      `                      className="flex-1 rounded-t bg-indigo-600/40"`,
      `                      style={{ height: \`\${20 + Math.random() * 80}%\` }}`,
      `                    />`,
      `                  ))}`,
      `                </div>`,
      `              </div>`,
      `            </div>`,
      `          </div>`,
      `        </div>`,
      `      </div>`,
      `    </section>`,
      `  );`,
      `}`,
      "",
    ].join("\n"),
  },
];

interface ScaffoldContext {
  name: string;
  slug: string;
  slogan: string;
  audience: string;
  sessionId: string;
  date: string;
  features: string[];
  pricing: { name: string; price: string; features: string[] }[];
  routes: { path: string; label: string }[];
}

function buildScaffoldContext(session: AutopilotSession): ScaffoldContext {
  const name = session.projectName;
  const slug = name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
  const idea = session.projectIdea;

  return {
    name,
    slug,
    slogan: idea.length > 80 ? idea.slice(0, 77) + "..." : idea,
    audience: session.productType === "b2b-saas" ? "Businesses & Teams" : "Individual users & professionals",
    sessionId: session.sessionId,
    date: formatTimestamp(session.createdAt),
    features: [
      `AI-Powered ${name} Automation`,
      "Real-Time Dashboard & Analytics",
      "Multi-Agent Orchestration",
      "Secure API with Role-Based Access",
      "Autopilot Session Management",
    ],
    pricing: [
      { name: "Starter", price: "$0/mo", features: ["1 project", "Basic dashboard", "Community support"] },
      { name: "Pro", price: "$29/mo", features: ["Unlimited projects", "Advanced analytics", "Priority support", "API access"] },
      { name: "Enterprise", price: "Custom", features: ["SSO & SAML", "Dedicated infra", "SLA guarantee", "Custom integrations"] },
    ],
    routes: [
      { path: "/", label: "Landing" },
      { path: "/dashboard", label: "Dashboard" },
      { path: "/projects", label: "Projects" },
      { path: "/settings", label: "Settings" },
      { path: "/autopilot", label: "Autopilot" },
    ],
  };
}

/**
 * Generate a complete SaaS project scaffold in the workspace.
 * Returns an array of relative paths written, or empty array if workspace missing.
 */
export function generateProjectScaffold(session: AutopilotSession): string[] {
  const dir = workspaceDir(session.sessionId);
  if (!fs.existsSync(dir)) return [];

  const projectDir = path.join(dir, "project");
  ensureDir(projectDir);

  const ctx = buildScaffoldContext(session);
  const writtenPaths: string[] = [];

  for (const file of SCAFFOLD_FILES) {
    const fullPath = path.join(dir, file.path);

    // Prevent path traversal
    const resolved = path.resolve(fullPath);
    if (!resolved.startsWith(path.resolve(dir))) continue;

    const content = file.content(ctx);
    safeWriteFile(fullPath, content);
    writtenPaths.push(file.path);
  }

  // Auto-validate the generated scaffold
  validateGeneratedProject(session.sessionId);

  return writtenPaths;
}

/**
 * Check whether a project scaffold already exists in the workspace.
 */
export function projectScaffoldExists(sessionId: string): boolean {
  const dir = workspaceDir(sessionId);
  const pkgPath = path.join(dir, "project", "package.json");
  return fs.existsSync(pkgPath);
}

// ─── Internal ─────────────────────────────────────────────────────────────────

function formatLogEntries(logs: AutopilotLog[]): string {
  return logs
    .slice(0, 60)
    .map((log) => `[${formatTimestamp(log.timestamp)}] [${log.level.toUpperCase()}] [${log.agent}] ${log.message}`)
    .join("\n");
}
