import fs from "fs";
import path from "path";
import type { AutopilotPhase, AutopilotSession, AutopilotTask, AutopilotLog } from "./autopilotStore";
import { AUTOPILOT_PHASES } from "./autopilotStore";

// ─── Paths ──────────────────────────────────────────────────────────────────

const REPO_ROOT = path.resolve(process.cwd(), "..");
const WORKSPACES_ROOT = path.join(REPO_ROOT, "generated", "autopilot-workspaces");

function workspaceDir(sessionId: string): string {
  return path.join(WORKSPACES_ROOT, sessionId);
}

// ─── Types ──────────────────────────────────────────────────────────────────────

export interface WorkspaceFile {
  path: string;
  name: string;
  size: number;
  modifiedAt: string;
}

export interface WorkspaceSummary {
  sessionId: string;
  projectName: string;
  exists: boolean;
  fileCount: number;
  totalSize: number;
  files: WorkspaceFile[];
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function ensureDir(dir: string) {
  fs.mkdirSync(dir, { recursive: true });
}

function safeWriteFile(filePath: string, content: string) {
  ensureDir(path.dirname(filePath));
  fs.writeFileSync(filePath, content, "utf-8");
}

function formatTimestamp(iso: string): string {
  try {
    return new Date(iso).toISOString().replace("T", " ").slice(0, 19);
  } catch {
    return iso;
  }
}

const PHASE_FILE_MAP: Record<AutopilotPhase, string> = {
  idea:         "phases/01-idea-analysis.md",
  planning:     "phases/02-product-definition.md",
  architecture: "phases/03-architecture.md",
  frontend:     "phases/04-frontend-design.md",
  backend:      "phases/05-backend-implementation.md",
  validation:   "phases/06-validation.md",
  build:        "phases/07-build-preparation.md",
  runtime:      "phases/08-runtime-monitoring.md",
};

// ─── Public API ───────────────────────────────────────────────────────────────

/**
 * Create the workspace directory and initial files for a session.
 * Called at session creation or on first run-step if workspace missing.
 */
export function createWorkspaceForSession(session: AutopilotSession): void {
  const dir = workspaceDir(session.sessionId);
  ensureDir(dir);

  // README.md
  safeWriteFile(path.join(dir, "README.md"), [
    `# ${session.projectName}`,
    "",
    `> ${session.projectIdea}`,
    "",
    `**Session:** ${session.sessionId}`,
    `**Template:** ${session.template ?? "custom"}`,
    `**Stack:** ${session.stack ?? "nextjs-prisma"}`,
    `**Created:** ${formatTimestamp(session.createdAt)}`,
    `**Provider:** NVIDIA API (Nemotron)`,
    "",
    "This workspace was generated by AI Company OS Autopilot.",
    "",
  ].join("\n"));

  // roadmap.md
  safeWriteFile(path.join(dir, "roadmap.md"), [
    `# Roadmap — ${session.projectName}`,
    "",
    ...session.roadmap.map((step, i) => `${i + 1}. ${step}`),
    "",
  ].join("\n"));

  // tasks.json
  safeWriteFile(path.join(dir, "tasks.json"), JSON.stringify(session.tasks, null, 2) + "\n");

  // logs.md
  safeWriteFile(path.join(dir, "logs.md"), [
    `# Autopilot Logs — ${session.projectName}`,
    "",
    formatLogEntries(session.logs),
    "",
  ].join("\n"));

  // Phase files: create initial stubs
  ensureDir(path.join(dir, "phases"));
  for (const phase of AUTOPILOT_PHASES) {
    const phaseFile = path.join(dir, PHASE_FILE_MAP[phase.id]);
    if (!fs.existsSync(phaseFile)) {
      safeWriteFile(phaseFile, [
        `# ${phase.label}`,
        "",
        `**Agent:** ${phase.agent}`,
        `**Provider:** NVIDIA API`,
        "",
        "_This file will be populated as the autopilot progresses through this phase._",
        "",
      ].join("\n"));
    }
  }
}

/**
 * Write or update a file in the workspace.
 */
export function writeWorkspaceFile(sessionId: string, relativePath: string, content: string): boolean {
  const dir = workspaceDir(sessionId);
  const filePath = path.join(dir, relativePath);

  // Prevent path traversal
  const resolved = path.resolve(filePath);
  if (!resolved.startsWith(path.resolve(dir))) return false;

  safeWriteFile(filePath, content);
  return true;
}

/**
 * Read a file from the workspace. Returns null if not found.
 */
export function readWorkspaceFile(sessionId: string, relativePath: string): string | null {
  const dir = workspaceDir(sessionId);
  const filePath = path.join(dir, relativePath);

  const resolved = path.resolve(filePath);
  if (!resolved.startsWith(path.resolve(dir))) return null;

  if (!fs.existsSync(filePath)) return null;
  try {
    return fs.readFileSync(filePath, "utf-8");
  } catch {
    return null;
  }
}

/**
 * List all files in the workspace.
 */
export function listWorkspaceFiles(sessionId: string): WorkspaceFile[] {
  const dir = workspaceDir(sessionId);
  if (!fs.existsSync(dir)) return [];

  const files: WorkspaceFile[] = [];

  function walk(currentDir: string, prefix: string) {
    const entries = fs.readdirSync(currentDir, { withFileTypes: true });
    for (const entry of entries) {
      const fullPath = path.join(currentDir, entry.name);
      const relPath = prefix ? `${prefix}/${entry.name}` : entry.name;
      if (entry.isDirectory()) {
        walk(fullPath, relPath);
      } else if (entry.isFile()) {
        try {
          const stat = fs.statSync(fullPath);
          files.push({
            path: relPath,
            name: entry.name,
            size: stat.size,
            modifiedAt: stat.mtime.toISOString(),
          });
        } catch {
          // skip unreadable files
        }
      }
    }
  }

  walk(dir, "");
  return files.sort((a, b) => a.path.localeCompare(b.path));
}

/**
 * Get a summary of the workspace.
 */
export function getWorkspaceSummary(sessionId: string): WorkspaceSummary {
  const dir = workspaceDir(sessionId);
  const exists = fs.existsSync(dir);
  const files = exists ? listWorkspaceFiles(sessionId) : [];
  const totalSize = files.reduce((sum, f) => sum + f.size, 0);

  let projectName = sessionId;
  if (exists) {
    const readmePath = path.join(dir, "README.md");
    if (fs.existsSync(readmePath)) {
      try {
        const firstLine = fs.readFileSync(readmePath, "utf-8").split("\n")[0] ?? "";
        const match = firstLine.match(/^#\s+(.+)$/);
        if (match) projectName = match[1];
      } catch {
        // ignore
      }
    }
  }

  return { sessionId, projectName, exists, fileCount: files.length, totalSize, files };
}

/**
 * Update workspace files after a run-step completes.
 * - Update tasks.json
 * - Append to logs.md
 * - Update the phase file if the task completed
 */
export function updateWorkspaceAfterStep(
  sessionId: string,
  tasks: AutopilotTask[],
  logs: AutopilotLog[],
  completedTask: AutopilotTask | null,
): void {
  const dir = workspaceDir(sessionId);
  if (!fs.existsSync(dir)) return;

  // Update tasks.json
  safeWriteFile(path.join(dir, "tasks.json"), JSON.stringify(tasks, null, 2) + "\n");

  // Update logs.md
  safeWriteFile(path.join(dir, "logs.md"), [
    `# Autopilot Logs`,
    "",
    formatLogEntries(logs),
    "",
  ].join("\n"));

  // Update phase file for the completed task
  if (completedTask && completedTask.status === "completed") {
    const phaseFile = PHASE_FILE_MAP[completedTask.phase as AutopilotPhase];
    if (phaseFile) {
      const phaseInfo = AUTOPILOT_PHASES.find((p) => p.id === completedTask.phase);
      const phaseTasks = tasks.filter((t) => t.phase === completedTask.phase);

      safeWriteFile(path.join(dir, phaseFile), [
        `# ${phaseInfo?.label ?? completedTask.phase}`,
        "",
        `**Agent:** ${completedTask.agent}`,
        `**Provider:** NVIDIA API`,
        `**Last updated:** ${formatTimestamp(completedTask.updatedAt)}`,
        "",
        "## Tasks",
        "",
        ...phaseTasks.map((t) => `- [${t.status === "completed" ? "x" : " "}] ${t.title} (${t.agent})`),
        "",
        "## Output",
        "",
        `Task **${completedTask.title}** completed by ${completedTask.agent}.`,
        "",
        `Description: ${completedTask.description}`,
        "",
        `_Generated by AI Company OS Autopilot — NVIDIA API_`,
        "",
      ].join("\n"));
    }
  }
}

// ─── Agent Artifact Definitions ────────────────────────────────────────────

const AGENT_ARTIFACTS: Record<string, { dir: string; files: { name: string; title: string; sections: (session: AutopilotSession, task: AutopilotTask) => string[] }[] }> = {
  product_agent: {
    dir: "product",
    files: [
      {
        name: "brief.md",
        title: "Product Brief",
        sections: (session, task) => [
          `# Product Brief — ${session.projectName}`,
          "",
          `**Session:** ${session.sessionId}`,
          `**Task:** ${task.id} — ${task.title}`,
          `**Agent:** product_agent`,
          `**Date:** ${formatTimestamp(task.updatedAt)}`,
          "",
          "## Objectives",
          "",
          `- ${task.description}`,
          `- Define ICP, value proposition and competitive positioning for ${session.projectName}`,
          `- Align product vision with market needs`,
          "",
          "## Key Decisions",
          "",
          `- Target market: early-adopter SaaS users seeking automation`,
          `- Core value prop: AI-driven workflow automation`,
          `- Differentiation: autonomous multi-agent orchestration`,
          `- MVP scope defined per roadmap priorities`,
          "",
          "## Next Actions",
          "",
          "- Validate user stories with target personas",
          "- Prioritize features for MVP release",
          "- Map customer journey and onboarding flow",
          "",
          `_Generated by AI Company OS Autopilot — NVIDIA API_`,
          "",
        ],
      },
      {
        name: "user-stories.md",
        title: "User Stories",
        sections: (session, task) => [
          `# User Stories — ${session.projectName}`,
          "",
          `**Session:** ${session.sessionId}`,
          `**Task:** ${task.id} — ${task.title}`,
          `**Agent:** product_agent`,
          `**Date:** ${formatTimestamp(task.updatedAt)}`,
          "",
          "## Core Stories",
          "",
          `1. **As a** user, **I want to** launch an autopilot session, **so that** I can build my product autonomously.`,
          `2. **As a** user, **I want to** monitor agent progress in real-time, **so that** I can stay informed without manual checking.`,
          `3. **As a** user, **I want to** review generated artifacts, **so that** I can validate quality and provide feedback.`,
          `4. **As a** user, **I want to** pause/resume execution, **so that** I retain control over the build process.`,
          `5. **As a** user, **I want to** see workspace files organized by agent, **so that** I can quickly find deliverables.`,
          "",
          "## Acceptance Criteria",
          "",
          "- Autopilot completes full 8-phase cycle",
          "- Each agent produces at least one artifact",
          "- User can view real-time logs and progress",
          "",
          `_Generated by AI Company OS Autopilot — NVIDIA API_`,
          "",
        ],
      },
    ],
  },
  architect_agent: {
    dir: "architecture",
    files: [
      {
        name: "system-design.md",
        title: "System Design",
        sections: (session, task) => [
          `# System Design — ${session.projectName}`,
          "",
          `**Session:** ${session.sessionId}`,
          `**Task:** ${task.id} — ${task.title}`,
          `**Agent:** architect_agent`,
          `**Date:** ${formatTimestamp(task.updatedAt)}`,
          "",
          "## Objectives",
          "",
          `- ${task.description}`,
          `- Define modular architecture with clear boundaries`,
          `- Ensure scalability and maintainability`,
          "",
          "## Architecture Overview",
          "",
          "```",
          "┌──────────────┐     ┌──────────────┐     ┌──────────────┐",
          "│   Frontend   │────▶│   API Layer   │────▶│   Database    │",
          "│  (Next.js)   │     │  (REST/WS)    │     │  (Postgres)   │",
          "└──────────────┘     └──────────────┘     └──────────────┘",
          "       │                    │                     │",
          "       ▼                    ▼                     ▼",
          "  UI Components      Business Logic         Data Models",
          "  Design System       Services              Migrations",
          "```",
          "",
          "## Key Decisions",
          "",
          `- Stack: ${session.stack ?? "nextjs-prisma"}`,
          "- Module boundaries: frontend / API / data layers",
          "- API pattern: REST with WebSocket for real-time events",
          "- Auth: JWT with refresh token rotation",
          "",
          "## Next Actions",
          "",
          "- Finalize data model and API surface",
          "- Define service contracts between modules",
          "- Document integration patterns",
          "",
          `_Generated by AI Company OS Autopilot — NVIDIA API_`,
          "",
        ],
      },
      {
        name: "data-model.md",
        title: "Data Model",
        sections: (session, task) => [
          `# Data Model — ${session.projectName}`,
          "",
          `**Session:** ${session.sessionId}`,
          `**Task:** ${task.id} — ${task.title}`,
          `**Agent:** architect_agent`,
          `**Date:** ${formatTimestamp(task.updatedAt)}`,
          "",
          "## Objectives",
          "",
          `- ${task.description}`,
          "- Design normalized schema with clear relationships",
          "",
          "## Core Entities",
          "",
          "```prisma",
          "model User {",
          "  id        String   @id @default(cuid())",
          "  email     String   @unique",
          "  name      String?",
          "  role      Role     @default(USER)",
          "  createdAt DateTime @default(now())",
          "}",
          "",
          "model Project {",
          "  id          String   @id @default(cuid())",
          "  name        String",
          "  description String?",
          "  ownerId     String",
          "  owner       User     @relation(fields: [ownerId], references: [id])",
          "  createdAt   DateTime @default(now())",
          "}",
          "",
          "enum Role { USER ADMIN }",
          "```",
          "",
          "## Key Decisions",
          "",
          "- UUID-based primary keys (cuid)",
          "- Soft delete via status fields",
          "- Audit trail via createdAt/updatedAt",
          "",
          "## Next Actions",
          "",
          "- Implement Prisma migrations",
          "- Add seed data for development",
          "- Define API DTOs matching models",
          "",
          `_Generated by AI Company OS Autopilot — NVIDIA API_`,
          "",
        ],
      },
    ],
  },
  frontend_agent: {
    dir: "frontend",
    files: [
      {
        name: "ui-plan.md",
        title: "UI Plan",
        sections: (session, task) => [
          `# UI Plan — ${session.projectName}`,
          "",
          `**Session:** ${session.sessionId}`,
          `**Task:** ${task.id} — ${task.title}`,
          `**Agent:** frontend_agent`,
          `**Date:** ${formatTimestamp(task.updatedAt)}`,
          "",
          "## Objectives",
          "",
          `- ${task.description}`,
          "- Design responsive, accessible UI with consistent design system",
          "",
          "## Pages & Components",
          "",
          "| Page | Components | Priority |",
          "|------|-----------|----------|",
          "| Dashboard | Stats, Charts, Activity Feed | P0 |",
          "| Onboarding | Step Wizard, Progress Bar | P0 |",
          "| Settings | Form, Toggle, Select | P1 |",
          "| Workspace | FileTree, Preview, Editor | P1 |",
          "",
          "## Design System",
          "",
          "- Colors: dark theme with accent highlights",
          "- Typography: system font stack (ui-monospace, sans-serif)",
          "- Spacing: 4px base unit",
          "- Components: Button, Card, Badge, Modal, Toast",
          "",
          "## Key Decisions",
          "",
          "- Dark-first design with accent colors",
          "- Responsive grid layout (mobile-friendly)",
          "- Component library built in-house",
          "",
          "## Next Actions",
          "",
          "- Build component library foundations",
          "- Implement dashboard layout",
          "- Add animations and transitions",
          "",
          `_Generated by AI Company OS Autopilot — NVIDIA API_`,
          "",
        ],
      },
      {
        name: "routes.md",
        title: "Routes & Navigation",
        sections: (session, task) => [
          `# Routes & Navigation — ${session.projectName}`,
          "",
          `**Session:** ${session.sessionId}`,
          `**Task:** ${task.id} — ${task.title}`,
          `**Agent:** frontend_agent`,
          `**Date:** ${formatTimestamp(task.updatedAt)}`,
          "",
          "## Route Map",
          "",
          "| Route | Page | Auth |",
          "|-------|------|------|",
          "| `/` | Landing | No |",
          "| `/dashboard` | Dashboard | Yes |",
          "| `/projects` | Project List | Yes |",
          "| `/projects/new` | Create Project | Yes |",
          "| `/settings` | Settings | Yes |",
          "| `/autopilot` | Autopilot Sessions | Yes |",
          "| `/autopilot/[id]` | Session Detail | Yes |",
          "",
          "## Navigation Structure",
          "",
          "- Sidebar: Dashboard, Projects, Autopilot, Logs, Settings",
          "- Breadcrumbs: contextual navigation per page",
          "- Quick actions: header-level shortcuts",
          "",
          "## Key Decisions",
          "",
          "- Next.js App Router with server components",
          "- Client-side navigation with Next Link",
          "- Protected routes via middleware",
          "",
          "## Next Actions",
          "",
          "- Implement route guards",
          "- Build sidebar navigation",
          "- Add page transition animations",
          "",
          `_Generated by AI Company OS Autopilot — NVIDIA API_`,
          "",
        ],
      },
    ],
  },
  backend_agent: {
    dir: "backend",
    files: [
      {
        name: "api-plan.md",
        title: "API Plan",
        sections: (session, task) => [
          `# API Plan — ${session.projectName}`,
          "",
          `**Session:** ${session.sessionId}`,
          `**Task:** ${task.id} — ${task.title}`,
          `**Agent:** backend_agent`,
          `**Date:** ${formatTimestamp(task.updatedAt)}`,
          "",
          "## Objectives",
          "",
          `- ${task.description}`,
          "- Design RESTful API with consistent patterns",
          "",
          "## API Endpoints",
          "",
          "| Method | Path | Description | Auth |",
          "|--------|------|-------------|------|",
          "| POST | /api/auth/login | Login | No |",
          "| POST | /api/auth/register | Register | No |",
          "| GET | /api/projects | List projects | Yes |",
          "| POST | /api/projects | Create project | Yes |",
          "| GET | /api/projects/:id | Get project | Yes |",
          "| GET | /api/autopilot/sessions | List sessions | Yes |",
          "| POST | /api/autopilot/sessions | Create session | Yes |",
          "| POST | /api/autopilot/sessions/:id/run-step | Run step | Yes |",
          "",
          "## Key Decisions",
          "",
          "- RESTful pattern with consistent response shape",
          "- JWT auth with refresh tokens",
          "- Rate limiting: 100 req/min per user",
          "- Error format: { ok: false, message: string }",
          "",
          "## Next Actions",
          "",
          "- Implement auth middleware",
          "- Build CRUD routes for core entities",
          "- Add request validation schemas",
          "",
          `_Generated by AI Company OS Autopilot — NVIDIA API_`,
          "",
        ],
      },
      {
        name: "services.md",
        title: "Services Layer",
        sections: (session, task) => [
          `# Services Layer — ${session.projectName}`,
          "",
          `**Session:** ${session.sessionId}`,
          `**Task:** ${task.id} — ${task.title}`,
          `**Agent:** backend_agent`,
          `**Date:** ${formatTimestamp(task.updatedAt)}`,
          "",
          "## Objectives",
          "",
          `- ${task.description}`,
          "- Define business logic services with clear contracts",
          "",
          "## Services",
          "",
          "### AuthService",
          "- login(email, password) → { token, refreshToken }",
          "- register(data) → User",
          "- verifyToken(token) → Payload",
          "",
          "### ProjectService",
          "- list(userId) → Project[]",
          "- create(data) → Project",
          "- getById(id) → Project | null",
          "",
          "### AutopilotService",
          "- createSession(input) → Session",
          "- runStep(sessionId) → RunStepResult",
          "- runAll(sessionId) → RunAllResult",
          "",
          "## Key Decisions",
          "",
          "- Service layer pattern (controller → service → repo)",
          "- Dependency injection for testability",
          "- Transactional writes for data integrity",
          "",
          "## Next Actions",
          "",
          "- Implement service interfaces",
          "- Add unit tests for core logic",
          "- Wire services to API routes",
          "",
          `_Generated by AI Company OS Autopilot — NVIDIA API_`,
          "",
        ],
      },
    ],
  },
  qa_agent: {
    dir: "qa",
    files: [
      {
        name: "test-plan.md",
        title: "Test Plan",
        sections: (session, task) => [
          `# Test Plan — ${session.projectName}`,
          "",
          `**Session:** ${session.sessionId}`,
          `**Task:** ${task.id} — ${task.title}`,
          `**Agent:** qa_agent`,
          `**Date:** ${formatTimestamp(task.updatedAt)}`,
          "",
          "## Objectives",
          "",
          `- ${task.description}`,
          "- Ensure comprehensive test coverage across all layers",
          "",
          "## Test Matrix",
          "",
          "| Layer | Type | Count | Coverage |",
          "|-------|------|-------|----------|",
          "| Unit | Service logic | 20+ | >80% |",
          "| Integration | API routes | 15+ | >70% |",
          "| E2E | Critical flows | 5+ | 100% smoke |",
          "| Contract | API shape | 10+ | All endpoints |",
          "",
          "## Test Categories",
          "",
          "1. **Unit Tests** — services, stores, helpers",
          "2. **Integration Tests** — API routes with mocked DB",
          "3. **Smoke Tests** — build succeeds, pages render",
          "4. **Security Tests** — auth, path traversal, XSS",
          "",
          "## Key Decisions",
          "",
          "- Vitest for unit/integration",
          "- React Testing Library for component tests",
          "- Deterministic test data via factories",
          "",
          "## Next Actions",
          "",
          "- Write unit test suite for core stores",
          "- Add integration tests for API routes",
          "- Set up CI test pipeline",
          "",
          `_Generated by AI Company OS Autopilot — NVIDIA API_`,
          "",
        ],
      },
      {
        name: "risks.md",
        title: "Risks & Mitigations",
        sections: (session, task) => [
          `# Risks & Mitigations — ${session.projectName}`,
          "",
          `**Session:** ${session.sessionId}`,
          `**Task:** ${task.id} — ${task.title}`,
          `**Agent:** qa_agent`,
          `**Date:** ${formatTimestamp(task.updatedAt)}`,
          "",
          "## Identified Risks",
          "",
          "| # | Risk | Severity | Likelihood | Mitigation |",
          "|---|------|----------|------------|------------|",
          "| 1 | NVIDIA API downtime | High | Low | Fallback to local simulation |",
          "| 2 | Data loss on session crash | High | Medium | JSON persistence + workspace backup |",
          "| 3 | Path traversal in workspace | High | Low | Resolved path validation |",
          "| 4 | Race condition on concurrent run-step | Medium | Medium | Session status lock |",
          "| 5 | Stale workspace files | Low | Medium | Auto-refresh on each step |",
          "",
          "## Security Considerations",
          "",
          "- API keys never logged or written to workspace",
          "- Path traversal protected on all file operations",
          "- Input validation on all API endpoints",
          "",
          "## Key Decisions",
          "",
          "- Fail-safe defaults: all writes validated",
          "- Rate-limited execution to prevent resource exhaustion",
          "- Workspace files are read-only for agents",
          "",
          "## Next Actions",
          "",
          "- Run vulnerability scan on dependencies",
          "- Add security-focused integration tests",
          "- Verify all error paths have safe fallbacks",
          "",
          `_Generated by AI Company OS Autopilot — NVIDIA API_`,
          "",
        ],
      },
    ],
  },
  devops_agent: {
    dir: "devops",
    files: [
      {
        name: "deployment-plan.md",
        title: "Deployment Plan",
        sections: (session, task) => [
          `# Deployment Plan — ${session.projectName}`,
          "",
          `**Session:** ${session.sessionId}`,
          `**Task:** ${task.id} — ${task.title}`,
          `**Agent:** devops_agent`,
          `**Date:** ${formatTimestamp(task.updatedAt)}`,
          "",
          "## Objectives",
          "",
          `- ${task.description}`,
          "- Define reliable deployment workflow with rollback capability",
          "",
          "## Deployment Strategy",
          "",
          "| Stage | Environment | Trigger |",
          "|-------|-------------|---------|",
          "| Build | CI runner | Push to main |",
          "| Test | CI runner | After build |",
          "| Staging | staging.example.com | After test pass |",
          "| Production | example.com | Manual approval |",
          "",
          "## Infrastructure",
          "",
          "- Hosting: Vercel (frontend) + Railway (backend)",
          "- Database: managed PostgreSQL",
          "- CI/CD: GitHub Actions",
          "- Monitoring: built-in runtime health checks",
          "",
          "## Key Decisions",
          "",
          "- Blue-green deployment for zero downtime",
          "- Feature flags for progressive rollout",
          "- Automated rollback on health check failure",
          "",
          "## Next Actions",
          "",
          "- Set up GitHub Actions workflow",
          "- Configure staging environment",
          "- Implement health check endpoint",
          "",
          `_Generated by AI Company OS Autopilot — NVIDIA API_`,
          "",
        ],
      },
      {
        name: "env-checklist.md",
        title: "Environment Checklist",
        sections: (session, task) => [
          `# Environment Checklist — ${session.projectName}`,
          "",
          `**Session:** ${session.sessionId}`,
          `**Task:** ${task.id} — ${task.title}`,
          `**Agent:** devops_agent`,
          `**Date:** ${formatTimestamp(task.updatedAt)}`,
          "",
          "## Required Environment Variables",
          "",
          "| Variable | Purpose | Required |",
          "|----------|---------|----------|",
          "| DATABASE_URL | Database connection | Yes |",
          "| NVIDIA_API_KEY | AI inference provider | Yes |",
          "| NEXTAUTH_SECRET | Auth encryption | Yes |",
          "| NODE_ENV | Runtime mode | Yes |",
          "",
          "## Pre-Deployment Checklist",
          "",
          "- [ ] All environment variables set",
          "- [ ] Database migrations applied",
          "- [ ] Build succeeds (`npm run build`)",
          "- [ ] Tests pass (`npm test`)",
          "- [ ] No secrets in source code",
          "- [ ] Health check endpoint responds",
          "- [ ] SSL certificate valid",
          "",
          "## Key Decisions",
          "",
          "- Secrets via environment variables only",
          "- .env.example committed, .env ignored",
          "- Runtime health monitoring on /api/runtime/status",
          "",
          "## Next Actions",
          "",
          "- Verify all env vars in staging",
          "- Run full smoke test suite",
          "- Confirm monitoring alerts are active",
          "",
          `_Generated by AI Company OS Autopilot — NVIDIA API_`,
          "",
        ],
      },
    ],
  },
};

/**
 * Generate or update agent artifact files in the workspace.
 * Returns an array of relative paths for the files that were written.
 */
export function generateAgentArtifact(session: AutopilotSession, task: AutopilotTask): string[] {
  const config = AGENT_ARTIFACTS[task.agent];
  if (!config) return [];

  const dir = workspaceDir(session.sessionId);
  if (!fs.existsSync(dir)) return [];

  const artifactDir = path.join(dir, config.dir);
  ensureDir(artifactDir);

  const writtenPaths: string[] = [];

  for (const file of config.files) {
    const relPath = `${config.dir}/${file.name}`;
    const fullPath = path.join(dir, relPath);

    // Prevent path traversal
    const resolved = path.resolve(fullPath);
    if (!resolved.startsWith(path.resolve(dir))) continue;

    const content = file.sections(session, task).join("\n");
    safeWriteFile(fullPath, content);
    writtenPaths.push(relPath);
  }

  return writtenPaths;
}

// ─── Internal ─────────────────────────────────────────────────────────────────

function formatLogEntries(logs: AutopilotLog[]): string {
  return logs
    .slice(0, 60)
    .map((log) => `[${formatTimestamp(log.timestamp)}] [${log.level.toUpperCase()}] [${log.agent}] ${log.message}`)
    .join("\n");
}
