import fs from "fs";
import path from "path";
import type { AutopilotPhase, AutopilotSession, AutopilotTask, AutopilotLog } from "./autopilotStore";
import { AUTOPILOT_PHASES } from "./autopilotStore";

// ─── Paths ──────────────────────────────────────────────────────────────────

const REPO_ROOT = path.resolve(process.cwd(), "..");
const WORKSPACES_ROOT = path.join(REPO_ROOT, "generated", "autopilot-workspaces");

function workspaceDir(sessionId: string): string {
  return path.join(WORKSPACES_ROOT, sessionId);
}

// ─── Types ──────────────────────────────────────────────────────────────────────

export interface WorkspaceFile {
  path: string;
  name: string;
  size: number;
  modifiedAt: string;
}

export interface WorkspaceSummary {
  sessionId: string;
  projectName: string;
  exists: boolean;
  fileCount: number;
  totalSize: number;
  files: WorkspaceFile[];
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function ensureDir(dir: string) {
  fs.mkdirSync(dir, { recursive: true });
}

function safeWriteFile(filePath: string, content: string) {
  ensureDir(path.dirname(filePath));
  fs.writeFileSync(filePath, content, "utf-8");
}

function formatTimestamp(iso: string): string {
  try {
    return new Date(iso).toISOString().replace("T", " ").slice(0, 19);
  } catch {
    return iso;
  }
}

const PHASE_FILE_MAP: Record<AutopilotPhase, string> = {
  idea:         "phases/01-idea-analysis.md",
  planning:     "phases/02-product-definition.md",
  architecture: "phases/03-architecture.md",
  frontend:     "phases/04-frontend-design.md",
  backend:      "phases/05-backend-implementation.md",
  validation:   "phases/06-validation.md",
  build:        "phases/07-build-preparation.md",
  runtime:      "phases/08-runtime-monitoring.md",
};

// ─── Public API ───────────────────────────────────────────────────────────────

/**
 * Create the workspace directory and initial files for a session.
 * Called at session creation or on first run-step if workspace missing.
 */
export function createWorkspaceForSession(session: AutopilotSession): void {
  const dir = workspaceDir(session.sessionId);
  ensureDir(dir);

  // README.md
  safeWriteFile(path.join(dir, "README.md"), [
    `# ${session.projectName}`,
    "",
    `> ${session.projectIdea}`,
    "",
    `**Session:** ${session.sessionId}`,
    `**Template:** ${session.template ?? "custom"}`,
    `**Stack:** ${session.stack ?? "nextjs-prisma"}`,
    `**Created:** ${formatTimestamp(session.createdAt)}`,
    `**Provider:** NVIDIA API (Nemotron)`,
    "",
    "This workspace was generated by AI Company OS Autopilot.",
    "",
  ].join("\n"));

  // roadmap.md
  safeWriteFile(path.join(dir, "roadmap.md"), [
    `# Roadmap — ${session.projectName}`,
    "",
    ...session.roadmap.map((step, i) => `${i + 1}. ${step}`),
    "",
  ].join("\n"));

  // tasks.json
  safeWriteFile(path.join(dir, "tasks.json"), JSON.stringify(session.tasks, null, 2) + "\n");

  // logs.md
  safeWriteFile(path.join(dir, "logs.md"), [
    `# Autopilot Logs — ${session.projectName}`,
    "",
    formatLogEntries(session.logs),
    "",
  ].join("\n"));

  // Phase files: create initial stubs
  ensureDir(path.join(dir, "phases"));
  for (const phase of AUTOPILOT_PHASES) {
    const phaseFile = path.join(dir, PHASE_FILE_MAP[phase.id]);
    if (!fs.existsSync(phaseFile)) {
      safeWriteFile(phaseFile, [
        `# ${phase.label}`,
        "",
        `**Agent:** ${phase.agent}`,
        `**Provider:** NVIDIA API`,
        "",
        "_This file will be populated as the autopilot progresses through this phase._",
        "",
      ].join("\n"));
    }
  }
}

/**
 * Write or update a file in the workspace.
 */
export function writeWorkspaceFile(sessionId: string, relativePath: string, content: string): boolean {
  const dir = workspaceDir(sessionId);
  const filePath = path.join(dir, relativePath);

  // Prevent path traversal
  const resolved = path.resolve(filePath);
  if (!resolved.startsWith(path.resolve(dir))) return false;

  safeWriteFile(filePath, content);
  return true;
}

/**
 * Read a file from the workspace. Returns null if not found.
 */
export function readWorkspaceFile(sessionId: string, relativePath: string): string | null {
  const dir = workspaceDir(sessionId);
  const filePath = path.join(dir, relativePath);

  const resolved = path.resolve(filePath);
  if (!resolved.startsWith(path.resolve(dir))) return null;

  if (!fs.existsSync(filePath)) return null;
  try {
    return fs.readFileSync(filePath, "utf-8");
  } catch {
    return null;
  }
}

/**
 * List all files in the workspace.
 */
export function listWorkspaceFiles(sessionId: string): WorkspaceFile[] {
  const dir = workspaceDir(sessionId);
  if (!fs.existsSync(dir)) return [];

  const files: WorkspaceFile[] = [];

  function walk(currentDir: string, prefix: string) {
    const entries = fs.readdirSync(currentDir, { withFileTypes: true });
    for (const entry of entries) {
      const fullPath = path.join(currentDir, entry.name);
      const relPath = prefix ? `${prefix}/${entry.name}` : entry.name;
      if (entry.isDirectory()) {
        walk(fullPath, relPath);
      } else if (entry.isFile()) {
        try {
          const stat = fs.statSync(fullPath);
          files.push({
            path: relPath,
            name: entry.name,
            size: stat.size,
            modifiedAt: stat.mtime.toISOString(),
          });
        } catch {
          // skip unreadable files
        }
      }
    }
  }

  walk(dir, "");
  return files.sort((a, b) => a.path.localeCompare(b.path));
}

/**
 * Get a summary of the workspace.
 */
export function getWorkspaceSummary(sessionId: string): WorkspaceSummary {
  const dir = workspaceDir(sessionId);
  const exists = fs.existsSync(dir);
  const files = exists ? listWorkspaceFiles(sessionId) : [];
  const totalSize = files.reduce((sum, f) => sum + f.size, 0);

  let projectName = sessionId;
  if (exists) {
    const readmePath = path.join(dir, "README.md");
    if (fs.existsSync(readmePath)) {
      try {
        const firstLine = fs.readFileSync(readmePath, "utf-8").split("\n")[0] ?? "";
        const match = firstLine.match(/^#\s+(.+)$/);
        if (match) projectName = match[1];
      } catch {
        // ignore
      }
    }
  }

  return { sessionId, projectName, exists, fileCount: files.length, totalSize, files };
}

/**
 * Update workspace files after a run-step completes.
 * - Update tasks.json
 * - Append to logs.md
 * - Update the phase file if the task completed
 */
export function updateWorkspaceAfterStep(
  sessionId: string,
  tasks: AutopilotTask[],
  logs: AutopilotLog[],
  completedTask: AutopilotTask | null,
): void {
  const dir = workspaceDir(sessionId);
  if (!fs.existsSync(dir)) return;

  // Update tasks.json
  safeWriteFile(path.join(dir, "tasks.json"), JSON.stringify(tasks, null, 2) + "\n");

  // Update logs.md
  safeWriteFile(path.join(dir, "logs.md"), [
    `# Autopilot Logs`,
    "",
    formatLogEntries(logs),
    "",
  ].join("\n"));

  // Update phase file for the completed task
  if (completedTask && completedTask.status === "completed") {
    const phaseFile = PHASE_FILE_MAP[completedTask.phase as AutopilotPhase];
    if (phaseFile) {
      const phaseInfo = AUTOPILOT_PHASES.find((p) => p.id === completedTask.phase);
      const phaseTasks = tasks.filter((t) => t.phase === completedTask.phase);

      safeWriteFile(path.join(dir, phaseFile), [
        `# ${phaseInfo?.label ?? completedTask.phase}`,
        "",
        `**Agent:** ${completedTask.agent}`,
        `**Provider:** NVIDIA API`,
        `**Last updated:** ${formatTimestamp(completedTask.updatedAt)}`,
        "",
        "## Tasks",
        "",
        ...phaseTasks.map((t) => `- [${t.status === "completed" ? "x" : " "}] ${t.title} (${t.agent})`),
        "",
        "## Output",
        "",
        `Task **${completedTask.title}** completed by ${completedTask.agent}.`,
        "",
        `Description: ${completedTask.description}`,
        "",
        `_Generated by AI Company OS Autopilot — NVIDIA API_`,
        "",
      ].join("\n"));
    }
  }
}

// ─── Internal ─────────────────────────────────────────────────────────────────

function formatLogEntries(logs: AutopilotLog[]): string {
  return logs
    .slice(0, 60)
    .map((log) => `[${formatTimestamp(log.timestamp)}] [${log.level.toUpperCase()}] [${log.agent}] ${log.message}`)
    .join("\n");
}
