import { describe, expect, it, vi, beforeEach } from "vitest";
import path from "path";

// ─── Mock setup ──────────────────────────────────────────────────────────────

const fileStore = new Map<string, string>();

vi.mock("fs", () => {
  const existsSync = vi.fn((p: string) => {
    if (fileStore.has(p)) return true;
    // Check if any stored path starts with this path (directory existence)
    for (const key of fileStore.keys()) {
      if (key.startsWith(p + "/") || key.startsWith(p + "\\")) return true;
    }
    return false;
  });

  const readdirSync = vi.fn((p: string) => {
    const prefix = p.endsWith(path.sep) ? p : p + path.sep;
    const prefixFwd = p.endsWith("/") ? p : p + "/";
    const seen = new Map<string, boolean>();
    const entries: { name: string; isFile: () => boolean; isDirectory: () => boolean }[] = [];

    for (const key of fileStore.keys()) {
      const rest = key.startsWith(prefix) ? key.slice(prefix.length)
        : key.startsWith(prefixFwd) ? key.slice(prefixFwd.length)
        : null;
      if (rest === null) continue;
      const name = rest.split(/[/\\]/)[0];
      if (!seen.has(name)) {
        seen.set(name, true);
        const isFile = !rest.includes("/") && !rest.includes("\\");
        entries.push({ name, isFile: () => isFile, isDirectory: () => !isFile });
      }
    }
    return entries;
  });

  const readFileSync = vi.fn((p: string) => fileStore.get(p) ?? "");
  const writeFileSync = vi.fn((p: string, data: string) => { fileStore.set(p, data); });
  const mkdirSync = vi.fn();

  return {
    default: { existsSync, readdirSync, readFileSync, writeFileSync, mkdirSync },
    existsSync, readdirSync, readFileSync, writeFileSync, mkdirSync,
  };
});

// ─── Path helpers ─────────────────────────────────────────────────────────────

const REPO_ROOT = path.resolve(process.cwd(), "..");
const WORKSPACES_ROOT = path.join(REPO_ROOT, "generated", "autopilot-workspaces");
const SESSION_ID = "ap-review-test-001";
const WS = path.join(WORKSPACES_ROOT, SESSION_ID);

function wsFile(rel: string): string {
  return path.join(WS, rel);
}

function reviewJsonPath(): string {
  return path.join(WS, "reviews", "review-report.json");
}

// ─── Fixtures ─────────────────────────────────────────────────────────────────

const RICH_CONTENT = [
  "# Analyze ICP and pain points for TestApp",
  "",
  "**Session:** ap-review-test-001",
  "**Task:** AP-001 — Analyze ICP",
  "**Agent:** product_agent",
  "**Date:** 2024-01-01 12:00:00",
  "",
  "## Objectives",
  "",
  "- Identify target customers for TestApp saas project",
  "- Define core value proposition",
  "- Map competitive landscape",
  "",
  "## Analysis",
  "",
  "This is a detailed analysis of the ICP for TestApp. The saas project targets",
  "small and medium businesses seeking workflow automation.",
  "",
  "Key findings: pain points around manual data entry, lack of integration,",
  "poor visibility into team productivity.",
  "",
  "## Next Actions",
  "",
  "- Validate user stories with 5 target personas",
  "- Prioritize features for MVP release",
  "- Map customer journey and onboarding flow",
  "",
  "_Generated by AI Company OS Autopilot — NVIDIA API_",
  "",
].join("\n");

const SHORT_CONTENT = "# Title\n\nToo short.";
const EMPTY_CONTENT = "   ";

// ─── Tests ────────────────────────────────────────────────────────────────────

describe("deliverableReview — scoring", () => {
  beforeEach(() => {
    fileStore.clear();
    vi.clearAllMocks();
  });

  it("scores empty content as 0 with draft status", async () => {
    fileStore.set(WS, "exists");
    fileStore.set(wsFile("product/brief.md"), EMPTY_CONTENT);

    const { reviewDeliverables } = await import("@/lib/deliverableReview");
    const report = reviewDeliverables(SESSION_ID, "TestApp", "saas_project");

    expect(report).not.toBeNull();
    const deliv = report!.deliverables.find((d) => d.name === "brief.md");
    expect(deliv?.score).toBe(0);
    expect(deliv?.status).toBe("draft");
    expect(deliv?.warnings).toContain("File is empty");
  });

  it("scores short content low with length warning", async () => {
    fileStore.set(WS, "exists");
    fileStore.set(wsFile("product/brief.md"), SHORT_CONTENT);

    const { reviewDeliverables } = await import("@/lib/deliverableReview");
    const report = reviewDeliverables(SESSION_ID, "TestApp", "saas_project");

    const deliv = report!.deliverables.find((d) => d.name === "brief.md");
    expect(deliv?.score).toBeLessThan(80);
    expect(deliv?.warnings.some((w) => w.includes("too short"))).toBe(true);
  });

  it("scores rich content as needs_review (score >= 80)", async () => {
    fileStore.set(WS, "exists");
    fileStore.set(wsFile("product/brief.md"), RICH_CONTENT);

    const { reviewDeliverables } = await import("@/lib/deliverableReview");
    const report = reviewDeliverables(SESSION_ID, "TestApp", "saas_project");

    const deliv = report!.deliverables.find((d) => d.name === "brief.md");
    expect(deliv?.score).toBeGreaterThanOrEqual(80);
    expect(deliv?.status).toBe("needs_review");
    expect(deliv?.warnings).toHaveLength(0);
  });

  it("all 5 checks pass for rich content (score = 100)", async () => {
    fileStore.set(WS, "exists");
    fileStore.set(wsFile("product/brief.md"), RICH_CONTENT);

    const { reviewDeliverables } = await import("@/lib/deliverableReview");
    const report = reviewDeliverables(SESSION_ID, "TestApp", "saas_project");

    const deliv = report!.deliverables.find((d) => d.name === "brief.md");
    expect(deliv?.score).toBe(100);
    expect(deliv?.checks.every((c) => c.passed)).toBe(true);
  });

  it("globalScore is average of all deliverable scores", async () => {
    fileStore.set(WS, "exists");
    fileStore.set(wsFile("product/brief.md"), RICH_CONTENT);    // 100
    fileStore.set(wsFile("product/user-stories.md"), EMPTY_CONTENT); // 0

    const { reviewDeliverables } = await import("@/lib/deliverableReview");
    const report = reviewDeliverables(SESSION_ID, "TestApp", "saas_project");

    expect(report!.globalScore).toBe(50);
  });

  it("returns null if workspace does not exist", async () => {
    const { reviewDeliverables } = await import("@/lib/deliverableReview");
    const report = reviewDeliverables("ap-nonexistent", "TestApp", "saas_project");
    expect(report).toBeNull();
  });

  it("saves report to reviews/review-report.json", async () => {
    fileStore.set(WS, "exists");
    fileStore.set(wsFile("product/brief.md"), RICH_CONTENT);

    const { reviewDeliverables } = await import("@/lib/deliverableReview");
    reviewDeliverables(SESSION_ID, "TestApp", "saas_project");

    expect(fileStore.has(reviewJsonPath())).toBe(true);
    const saved = JSON.parse(fileStore.get(reviewJsonPath())!) as { sessionId: string; globalScore: number };
    expect(saved.sessionId).toBe(SESSION_ID);
    expect(typeof saved.globalScore).toBe("number");
  });
});

describe("deliverableReview — approval workflow", () => {
  beforeEach(() => {
    fileStore.clear();
    vi.clearAllMocks();
    // Seed workspace + deliverable
    fileStore.set(WS, "exists");
    fileStore.set(wsFile("product/brief.md"), RICH_CONTENT);
  });

  it("approveDeliverable changes status to approved", async () => {
    const { reviewDeliverables, approveDeliverable } = await import("@/lib/deliverableReview");

    reviewDeliverables(SESSION_ID, "TestApp", "saas_project");
    const updated = approveDeliverable(SESSION_ID, "product/brief.md");

    expect(updated).not.toBeNull();
    const deliv = updated!.deliverables.find((d) => d.path === "product/brief.md");
    expect(deliv?.status).toBe("approved");
    expect(deliv?.approvedAt).toBeTruthy();
    expect(deliv?.rejectedAt).toBeUndefined();
  });

  it("rejectDeliverable changes status to rejected with reason", async () => {
    const { reviewDeliverables, rejectDeliverable } = await import("@/lib/deliverableReview");

    reviewDeliverables(SESSION_ID, "TestApp", "saas_project");
    const updated = rejectDeliverable(SESSION_ID, "product/brief.md", "Missing acceptance criteria");

    expect(updated).not.toBeNull();
    const deliv = updated!.deliverables.find((d) => d.path === "product/brief.md");
    expect(deliv?.status).toBe("rejected");
    expect(deliv?.rejectedAt).toBeTruthy();
    expect(deliv?.rejectionReason).toBe("Missing acceptance criteria");
    expect(deliv?.approvedAt).toBeUndefined();
  });

  it("clientReady is true only when all deliverables are approved", async () => {
    const { reviewDeliverables, approveDeliverable } = await import("@/lib/deliverableReview");

    // Two deliverables
    fileStore.set(wsFile("product/user-stories.md"), RICH_CONTENT);

    reviewDeliverables(SESSION_ID, "TestApp", "saas_project");

    // Approve one
    const after1 = approveDeliverable(SESSION_ID, "product/brief.md");
    expect(after1?.clientReady).toBe(false);

    // Approve second
    const after2 = approveDeliverable(SESSION_ID, "product/user-stories.md");
    expect(after2?.clientReady).toBe(true);
  });

  it("global status is approved when all deliverables are approved", async () => {
    const { reviewDeliverables, approveDeliverable } = await import("@/lib/deliverableReview");

    reviewDeliverables(SESSION_ID, "TestApp", "saas_project");
    const updated = approveDeliverable(SESSION_ID, "product/brief.md");

    expect(updated?.status).toBe("approved");
  });

  it("global status is rejected if any deliverable is rejected", async () => {
    const { reviewDeliverables, rejectDeliverable } = await import("@/lib/deliverableReview");

    fileStore.set(wsFile("product/user-stories.md"), RICH_CONTENT);
    reviewDeliverables(SESSION_ID, "TestApp", "saas_project");
    const updated = rejectDeliverable(SESSION_ID, "product/brief.md");

    expect(updated?.status).toBe("rejected");
    expect(updated?.clientReady).toBe(false);
  });

  it("loadReviewReport returns null when no report exists", async () => {
    const { loadReviewReport } = await import("@/lib/deliverableReview");
    const report = loadReviewReport("ap-no-session");
    expect(report).toBeNull();
  });

  it("loadReviewReport returns saved report", async () => {
    const { reviewDeliverables, loadReviewReport } = await import("@/lib/deliverableReview");

    reviewDeliverables(SESSION_ID, "TestApp", "saas_project");
    const loaded = loadReviewReport(SESSION_ID);

    expect(loaded).not.toBeNull();
    expect(loaded!.sessionId).toBe(SESSION_ID);
    expect(loaded!.deliverables.length).toBeGreaterThan(0);
  });

  it("approveDeliverable preserves approval on re-review", async () => {
    const { reviewDeliverables, approveDeliverable } = await import("@/lib/deliverableReview");

    reviewDeliverables(SESSION_ID, "TestApp", "saas_project");
    approveDeliverable(SESSION_ID, "product/brief.md");

    // Re-run review (simulates new step completing)
    const reReviewed = reviewDeliverables(SESSION_ID, "TestApp", "saas_project");
    const deliv = reReviewed!.deliverables.find((d) => d.path === "product/brief.md");

    // Status should still be approved (preserved)
    expect(deliv?.status).toBe("approved");
  });

  it("approveDeliverable returns null if no report exists", async () => {
    const { approveDeliverable } = await import("@/lib/deliverableReview");
    const result = approveDeliverable("ap-no-session", "product/brief.md");
    expect(result).toBeNull();
  });

  it("rejectDeliverable returns null if no report exists", async () => {
    const { rejectDeliverable } = await import("@/lib/deliverableReview");
    const result = rejectDeliverable("ap-no-session", "product/brief.md");
    expect(result).toBeNull();
  });
});
