"""Architect agent — generates architecture docs and infrastructure configs."""

import json
from .base_agent import BaseAgent


class ArchitectAgent(BaseAgent):
    name = "architect_agent"

    def run(self, task: dict, context: dict) -> dict:
        title = self.title(task)
        description = self.description(task)
        lowered = f"{title} {description}".lower()
        project = context.get("project_name", "project")

        files = {}

        if "api" in lowered or "spec" in lowered or "contract" in lowered:
            path = "docs/api-spec.md"
            files[path] = self._api_spec(title, description, project)
            print(f"  [{self.name}] generating {path}")

        if "infrastructure" in lowered or "system" in lowered or "architecture" in lowered:
            path = "docs/architecture.md"
            files[path] = self._architecture_doc(title, description, project)
            print(f"  [{self.name}] generating {path}")

        if "config" in lowered or "env" in lowered or "environment" in lowered:
            path = "docs/environment.md"
            files[path] = self._env_guide(title, description, project)
            print(f"  [{self.name}] generating {path}")

        if not files:
            # Generic architecture note
            path = f"docs/arch-{self.slug(task)}.md"
            files[path] = self._generic_note(title, description, project)
            print(f"  [{self.name}] generating {path}")

        return self._result(files, notes=f"Architecture artefacts for: {title}")

    # ------------------------------------------------------------------

    def _api_spec(self, title: str, description: str, project: str) -> str:
        return (
            f"# API Specification — {project}\n\n"
            f"## {title}\n\n"
            f"{description}\n\n"
            "## Base URL\n\n"
            "```\nhttp://localhost:3000/api\n```\n\n"
            "## Endpoints\n\n"
            "| Method | Path | Description |\n"
            "|--------|------|-------------|\n"
            "| GET | `/api/health` | Health check |\n"
            "| POST | `/api/auth` | Authenticate user |\n"
            "| GET | `/api/billing` | List plans |\n"
            "| POST | `/api/billing` | Subscribe to plan |\n\n"
            "## Authentication\n\n"
            "All protected endpoints require `Authorization: Bearer <token>` header.\n\n"
            "## Error Format\n\n"
            "```json\n{ \"error\": \"Message\", \"code\": 400 }\n```\n"
        )

    def _architecture_doc(self, title: str, description: str, project: str) -> str:
        return (
            f"# Architecture — {project}\n\n"
            f"## {title}\n\n"
            f"{description}\n\n"
            "## Stack\n\n"
            "- **Frontend**: Next.js 14 (App Router) + TypeScript + Tailwind CSS\n"
            "- **Backend**: Next.js API Routes (serverless)\n"
            "- **Database**: PostgreSQL via Prisma ORM\n"
            "- **Auth**: Custom token-based (demo) — swap for Clerk/NextAuth\n"
            "- **Billing**: Simulated — swap for Stripe\n\n"
            "## Key Modules\n\n"
            "```\napp/          Next.js pages and API routes\n"
            "lib/          Shared utilities (auth, billing, config)\n"
            "prisma/       Database schema\n"
            "agents/       AI Company OS specialized agents\n```\n\n"
            "## Data Flow\n\n"
            "```\nUser → Next.js Page → API Route → lib/ → Prisma → PostgreSQL\n```\n"
        )

    def _env_guide(self, title: str, description: str, project: str) -> str:
        return (
            f"# Environment Configuration — {project}\n\n"
            f"## {title}\n\n"
            f"{description}\n\n"
            "## Required Variables\n\n"
            "| Variable | Description | Example |\n"
            "|----------|-------------|--------|\n"
            "| `DATABASE_URL` | PostgreSQL connection string | `postgresql://user:pass@localhost:5432/db` |\n"
            "| `NEXT_PUBLIC_APP_URL` | Public app URL | `http://localhost:3000` |\n\n"
            "## Optional Variables\n\n"
            "| Variable | Description |\n"
            "|----------|-------------|\n"
            "| `STRIPE_SECRET_KEY` | Stripe secret key (when billing is live) |\n"
            "| `SMTP_HOST` | Email provider host |\n\n"
            "## Setup\n\n"
            "```bash\ncp .env.example .env.local\n# Fill in values\n```\n"
        )

    def _generic_note(self, title: str, description: str, project: str) -> str:
        return (
            f"# {title}\n\n"
            f"**Project:** {project}\n\n"
            f"{description}\n\n"
            "## Notes\n\n"
            "- Generated by architect_agent\n"
            "- Review and refine before implementation\n"
        )
