"""Product agent — generates roadmap notes, PRDs, and feature specs."""

from .base_agent import BaseAgent


class ProductAgent(BaseAgent):
    name = "product_agent"

    def run(self, task: dict, context: dict) -> dict:
        title = self.title(task)
        description = self.description(task)
        lowered = f"{title} {description}".lower()
        slug = self.slug(task)
        project = context.get("project_name", "project")
        roadmap = context.get("roadmap") or ""

        files = {}

        if "roadmap" in lowered:
            path = "docs/roadmap-update.md"
            files[path] = self._roadmap_update(title, description, project, roadmap)
            print(f"  [{self.name}] generating {path}")

        elif "prd" in lowered or "requirement" in lowered or "product requirement" in lowered:
            path = f"docs/prd-{slug}.md"
            files[path] = self._prd(title, description, project)
            print(f"  [{self.name}] generating {path}")

        elif "user story" in lowered or "feature" in lowered:
            path = f"docs/feature-{slug}.md"
            files[path] = self._feature_spec(title, description, project)
            print(f"  [{self.name}] generating {path}")

        else:
            path = f"docs/{slug}.md"
            files[path] = self._generic_spec(title, description, project)
            print(f"  [{self.name}] generating {path}")

        return self._result(files, notes=f"Product spec for: {title}")

    # ------------------------------------------------------------------

    def _roadmap_update(self, title: str, description: str, project: str, existing: str) -> str:
        return (
            f"# Roadmap Update — {project}\n\n"
            f"## {title}\n\n"
            f"{description}\n\n"
            "## Status: In Progress\n\n"
            "## Deliverables\n\n"
            "- [ ] Design approved\n"
            "- [ ] Implementation complete\n"
            "- [ ] Tests written\n"
            "- [ ] Deployed to staging\n\n"
            "---\n\n"
            "_Generated by product_agent_\n"
        )

    def _prd(self, title: str, description: str, project: str) -> str:
        return (
            f"# PRD — {title}\n\n"
            f"**Project:** {project}\n\n"
            "## Overview\n\n"
            f"{description}\n\n"
            "## Goals\n\n"
            "- Define the scope and acceptance criteria\n"
            "- Align engineering and design on the feature\n"
            "- Set success metrics\n\n"
            "## User Stories\n\n"
            "- As a gym owner, I want to … so that I can …\n"
            "- As a member, I want to … so that I can …\n\n"
            "## Acceptance Criteria\n\n"
            "- [ ] Feature works as described\n"
            "- [ ] Mobile responsive\n"
            "- [ ] No breaking changes to existing functionality\n\n"
            "## Out of Scope\n\n"
            "- Real payment processing (V1 is simulated)\n"
            "- Third-party auth provider (V1 uses demo tokens)\n"
        )

    def _feature_spec(self, title: str, description: str, project: str) -> str:
        return (
            f"# Feature Spec — {title}\n\n"
            f"**Project:** {project}\n\n"
            "## Summary\n\n"
            f"{description}\n\n"
            "## User Stories\n\n"
            "- As a user, I want this feature so that I can solve my problem\n\n"
            "## Design Notes\n\n"
            "- Follow existing UI patterns (Tailwind, dark sidebar for app pages)\n"
            "- Maintain accessibility (WCAG 2.1 AA)\n\n"
            "## Technical Notes\n\n"
            "- Use existing `lib/` utilities where possible\n"
            "- Add mock data to `lib/mock-data.ts` if needed\n"
        )

    def _generic_spec(self, title: str, description: str, project: str) -> str:
        return (
            f"# {title}\n\n"
            f"**Project:** {project}\n\n"
            f"{description}\n\n"
            "## Notes\n\n"
            "- Generated by product_agent\n"
            "- Refine this spec before implementation\n"
        )
